[parametric] Add Java library OTel support
DataDog/system-tests pull request #1056
Opened 2023-04-07 10:11 UTC by PerfectSlayer

## Description

This PR adds OpenTelemetry support to Java library client for parametric tests.

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if needed.

Once your PR is reviewed, you can merge it ! :heart:

2023-04-07 13:57 UTC, Kyle-Verhoog approved these changes

2023-04-07 15:36 UTC, cbeauchesne requested changes
Sone lint is required : `./format.sh`

2023-04-11 11:58 UTC, PerfectSlayer commented on parametric/test_otel_span_methods.py
This is expected as it requires a new release from the Java tracer.

> It requires some dd-trace-java instrumentation fixes (https://github.com/DataDog/dd-trace-java/pull/5037).

I plan to merge this PR as #1021 only once tracer is released.

2023-04-11 12:02 UTC, cbeauchesne commented on parametric/test_otel_span_methods.py
ok, I'll set it as a draft then.  You can set it back to nornal once you need a review

2023-04-11 12:04 UTC, PerfectSlayer commented on parametric/test_otel_span_methods.py
Ok. The PR is complete though.
I will mark it as ready once we did a release then.

2023-04-17 10:51 UTC, PerfectSlayer commented
The `1.12.0` version of Java tracer was just released. 
So it is ready for review @cbeauchesne

2023-04-18 09:39 UTC, cbeauchesne commented
relaunching the CI !

2023-04-19 10:38 UTC, PerfectSlayer commented
> It's still failing on java/parametric, is it expected ?

Looks like nobody is maintaining the docker image with the tracer... 
I will need to fix it myself or revert to the curl/wget solution to download the Java tracer.

But in the same time, the OTel tests changed again... I will deal with it later I guess 🤷

2023-04-21 11:28 UTC, PerfectSlayer commented
@cbeauchesne I updated it with the old way to get tracer and latest parametric tests state.

2023-04-21 12:48 UTC, cbeauchesne approved these changes

2023-04-21 12:48 UTC, merged