Add custom rules in embedded file
DataDog/system-tests pull request #1076
Opened 2023-04-14 12:36 UTC by anna-git

## Description

*Please include a short summary of the change*

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if needed.

Once your PR is reviewed, you can merge it ! :heart:

2023-04-18 08:04 UTC, smola approved these changes

2023-04-19 09:55 UTC, cbeauchesne requested changes
CI is failing on dotnet on this scenario

2023-04-20 14:09 UTC, anna-git commented
> CI is failing on dotnet on this scenario

Yes! The test should pass from tracer 2.30.0 and not 2.29.0 like I first added 🤦, it's changed now

2023-04-21 16:59 UTC, cbeauchesne approved these changes

2023-04-25 08:18 UTC, merged