Francois.mazeau/go srb tests
DataDog/system-tests pull request #1139
Opened 2023-05-03 13:53 UTC by Hellzy

## Description

## Motivation

## Additional notes

2023-05-15 11:02 UTC, Julio-Guerra approved these changes

2023-05-15 13:52 UTC, cbeauchesne requested changes
CI is failing on activated tests : https://github.com/DataDog/system-tests/actions/runs/4980232735/jobs/8912901655?pr=1139#step:28:583

2023-05-15 20:50 UTC, Julio-Guerra approved these changes

2023-05-16 07:47 UTC, smola approved these changes

2023-05-16 08:25 UTC, cbeauchesne approved these changes

2023-05-16 08:45 UTC, merged