Update IAST unvalidated redirect vulnerability
DataDog/system-tests pull request #1194
Opened 2023-05-19 08:42 UTC by jandro996

## Description

- Update sink test for unvalidated redirect vulnerability
- Add jersey and resteasy endpoints to test unvalidated redirect in header and location Response methods

## Motivation

Test unvalidated redirect vulnerability

2023-05-22 12:56 UTC, smola requested changes

2023-05-22 12:56 UTC, smola commented on tests/appsec/iast/sink/test_unvalidated_redirect.py
> +    sink_fixture_forward = SinkFixture(
We could just have a different file and class for `test_unvalidated_forward.py`, I'm fairly sure that the `@release` decorator and implementation timeframes will generally be quite different for both across languages.

2023-05-23 08:01 UTC, smola approved these changes

2023-05-30 08:50 UTC, cbeauchesne reviewed
I see some errors on CI, is it related ?

2023-06-02 08:28 UTC, jandro996 commented
> I see some errors on CI, is it related ?

I think that it's not related but let me update the PR and check again 👍

2023-06-02 11:08 UTC, jandro996 commented
@cbeauchesne I'm pretty sure that these fails are not related with the changes in this PR. It seems that many system-test PRs are failing due to the failing tasks right now

2023-06-02 13:41 UTC, cbeauchesne approved these changes

2023-06-16 07:35 UTC, smola requested changes

2023-06-16 07:35 UTC, smola commented on tests/appsec/iast/sink/test_unvalidated_redirect_forward.py
> +class TestUnvalidatedRedirect:
```suggestion
class TestUnvalidatedForward:
```

2023-06-20 09:10 UTC, smola approved these changes

2023-06-20 09:27 UTC, merged