Suspicious request blocking tests for Java
DataDog/system-tests pull request #1218
Opened 2023-05-30 15:18 UTC by smola

## Description

## Motivation

## Additional notes

2023-06-02 11:07 UTC, smola commented on tests/appsec/test_blocking_addresses.py
> +        assert self.rm_req_nonblock3.status_code == 200
`application/octet-stream` and `text/plain`, I'm changing the relevant endpoints to allow both, so they'll be 200 again.

2023-06-02 12:18 UTC, smola commented on tests/appsec/test_blocking_addresses.py
> +        assert self.rm_req_nonblock3.status_code == 200
Based on an offline discussion, I have added endpoints that accept application/octet-stream and text/plain for jax-rs. So the 415 case is gone.

However, in jax-rs, depending on the annotations, we'll treat text/plain as parsed body and block based on it. I have moved this case to a separate case and marked as irrelevant for jax-rs, as it seems we need some further discussion on this behavior.

2023-06-06 15:14 UTC, cbeauchesne requested changes
CI is failing on activated test

2023-06-07 14:28 UTC, smola commented
@cbeauchesne It's just that dd-trace-java snapshots stopped being updated in ghcr.io for a couple of weeks, I'm looking for someone who can fix this.

2023-06-12 08:47 UTC, cbeauchesne approved these changes

2023-06-14 14:18 UTC, merged