Increase max denylist size in the full_denylist scenarios
DataDog/system-tests pull request #1248
Opened 2023-06-07 13:45 UTC by M4TTRX

## Description

In the `APPSEC_BLOCKING_FULL_DENYLIST` scenario: 
- Increase the number of IPs blocked: 1250 ➡️  12500 (x10)
- Increase the number of users blocked: 1250 ➡️ 2500 (x2)
New total of entries blocked: 2500 ➡️ **15000**

Other changes:
- Added a block one ip and block one user test
- Only test the first and last IP blocked ip and user, to speed up the tests.
- 
## Motivation

One of our clients requires blocking of up to 15000 IPs at once. We are currently seeing if it would be possible in the next quater to increase the limit of IPs that can be blocked from 2500 IPs to 15000. This test is the first part that checks the feasibility of such increase.

## Reviewer checklist

* [ ] If this PR modify anything else than sctriclty the default scenario, then remove the `run-default-scenario` label
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Temove `run-default-scenario` label to run all scenarios ([more info](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions))

Once your PR is reviewed, you can merge it ! :heart:

2023-06-12 08:36 UTC, cbeauchesne requested changes
Some failure on java on this scenario.

2023-06-16 07:33 UTC, smola commented
@M4TTRX Feel free to add a `@bug(library="java", reason="RC payload limit")` to the failing test and move on. I'll modify it once we have a release with a fix.

2023-06-20 13:04 UTC, smola approved these changes

2023-06-20 13:41 UTC, simon-id approved these changes

2023-06-29 16:35 UTC, cbeauchesne requested changes

2023-06-30 13:18 UTC, cbeauchesne requested changes

2023-06-30 13:18 UTC, cbeauchesne commented on tests/appsec/test_user_blocking_full_denylist.py
> +            weblog.get("/users", params={"user": 1}),
either 0 - 2499, or 1 - 2500

2023-06-30 13:18 UTC, cbeauchesne commented on tests/appsec/test_blocking_addresses.py
>      """Test the addresses supported for blocking"""
Move up this docstring

2023-06-30 13:33 UTC, M4TTRX commented on tests/appsec/test_blocking_addresses.py
>      """Test the addresses supported for blocking"""
done

2023-06-30 13:33 UTC, M4TTRX commented on tests/appsec/test_user_blocking_full_denylist.py
> +            weblog.get("/users", params={"user": 1}),
done

2023-06-30 13:33 UTC, M4TTRX commented on tests/appsec/test_blocking_addresses.py
> +    """Test the blocking of one user"""
done

2023-06-30 13:33 UTC, M4TTRX commented on tests/appsec/test_blocking_addresses.py
> +    """Test the blocking of one IP"""
doen

2023-06-30 15:11 UTC, cbeauchesne approved these changes

2023-06-30 15:13 UTC, merged