Enable automated user events for ruby
DataDog/system-tests pull request #1387
Opened 2023-07-10 11:49 UTC by GustavoCaso

## Description

Add all the necessary work for enabling automated login events for Ruby. The code is on master, but we haven't yet released it. Still, this PR makes all the necessary work upfront to make sure once we release dd-trace-rb, we can enable the tests by changing the release version.

## Motivation

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] If this PR modifies anything else than strictly the default scenario, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/system-tests-ci.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com

2023-07-10 15:31 UTC, cbeauchesne commented on utils/build/docker/ruby/rails40.Dockerfile
> +RUN echo "#!/bin/bash\nbundle exec rake db:create db:migrate db:seed\nbundle exec thin start -p 7777" > app.sh
Is there a reason for Having `rake db:create db:migrate db:seed` at runtime rather during the build ?

2023-07-10 15:56 UTC, cbeauchesne requested changes

2023-07-10 15:56 UTC, cbeauchesne commented on tests/appsec/test_automated_login_events.py
> +        if context.library == "ruby":
Could you add methods to the class: 

```python
class Test_Login_Events:
    """ Test login success/failure use cases """

    @property
    def username_key(self):
       """ <Explanation why is it different> """
       return "user[username]" if "rails" in context.weblog_variant else "username"

    # same for password_key
```

Then, setup method will be all the same : 

```python
                weblog.post("/login?auth=local", data={self.username_key: self.USER, self.password_key: self.PASSWORD}),
```

2023-07-12 13:28 UTC, hoolioh approved these changes

2023-07-12 14:21 UTC, lloeki approved these changes
I don't see anything wild in there. LGTM.

We should find a way to make most of this weblog code shareable between Rails versions. I did it with Rails engines back in the day but engines create a bit of special cases (e.g they're nested rack apps) that would bias the tests, so I'm more thinking about e.g some dumb Ruby defining modules that get included in or extend controllers, and for migrations eschew activerecord in migrations and seeds and just run things that create the appropriate database and data (e.g restore a SQL dump or use something like https://github.com/lloeki/rebel)

2023-07-12 17:01 UTC, merged