Add IAST XSS system test
DataDog/system-tests pull request #1431
Opened 2023-07-24 09:40 UTC by jandro996

## Description
- Add XSS tests 
- Add Java XSS enpoints in:
   - spring-boot

## Motivation
Test XSS vulnerability

## Additional Notes
Some test are enabled for next dd-java-agent version (1.19.0)

2023-08-04 07:33 UTC, smola approved these changes

2023-08-07 10:52 UTC, manuel-alvarez-alvarez commented on utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
> +        return xssExamples.insecureXSS(response.getWriter(), request.getParameter("param"));
It's very weird that you return a string from your endpoint and use the writer of the response, your method should be void.

2023-08-16 09:08 UTC, cbeauchesne requested changes

2023-08-16 09:08 UTC, cbeauchesne commented on tests/appsec/iast/sink/test_xss.py
> +if context.library == "cpp":
Can you use the new manifest file for this : `manifests/cpp.yml` ? 

(Same for the `@released` below)

2023-08-17 09:33 UTC, cbeauchesne requested changes

2023-08-17 09:33 UTC, cbeauchesne commented on manifests/java.yml
> +    iast/:
`iast/` must be placed above `test_alpha.py`

I made a pretty agressive linter for this file , to help finding quickly the good location. Rules are : 

* folder must be placed before files
* then, name must be ordered alpabetically

2023-08-18 05:22 UTC, merged