Deserialize metric payload
DataDog/system-tests pull request #1529
Opened 2023-08-24 10:53 UTC by smola

## Description

## Motivation

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

2023-08-25 08:55 UTC, cbeauchesne requested changes
Could you also update `.github/workflows/update-agent-protobuf.yml` ?

2023-08-25 08:55 UTC, cbeauchesne commented on utils/proxy/_decoders/protobuf_schemas.py
> +print(list(_messages.keys()))
Forgot a print 😉

2023-08-30 07:43 UTC, cbeauchesne requested changes
The github action is not working, or do I miss something?

https://github.com/DataDog/system-tests/actions/runs/6022004668/job/16335882029

2023-08-30 11:06 UTC, smola commented
@cbeauchesne Fixed: https://github.com/DataDog/system-tests/actions/runs/6023993566/job/16341822346

2023-09-01 10:08 UTC, cbeauchesne approved these changes

2023-09-01 11:35 UTC, merged