Fix parametric tracer version for python
DataDog/system-tests pull request #1589
Opened 2023-09-13 11:05 UTC by robertomonteromiguel

## Description

We need to know the version of the tracer under test before running the tests, to make the @missing_feature annotations work.

## Motivation

In python need to ignore tests for specific versions of tracer

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

2023-09-14 11:11 UTC, bantonsson approved these changes
The common and Java parts look ok to me.

2023-09-14 17:22 UTC, marcotc approved these changes
:ruby: approved

2023-09-14 18:05 UTC, zacharycmontoya approved these changes
LGTM for .NET

2023-09-15 07:33 UTC, cbeauchesne requested changes

2023-09-15 07:33 UTC, cbeauchesne commented on utils/build/docker/dotnet/parametric/ddtracer_version.Dockerfile
> +RUN sh ddtracer_version.sh
As the sh file is mostly a one liner, you can shave it : 

```suggestion
RUN echo $(xmllint --xpath 'string(//Project/ItemGroup/PackageReference[@Include="Datadog.Trace.Bundle"]/@Version)' ApmTestClient.csproj) > SYSTEM_TESTS_LIBRARY_VERSION

```

2023-09-20 08:39 UTC, merged