[opentelemetry] Increase backend timeout and ignore if unable to fetch from backend
DataDog/system-tests pull request #1633
Opened 2023-09-28 12:49 UTC by songy23

## Description

Increase backend timeout and ignore if unable to fetch from backend.

If backend provides traces / series / logs, still perform the validation.

If the tests themselves cannot be built and run, tests still fail.

## Motivation

Deflake opentelemetry tests due to staging not being stable.

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

2023-09-29 14:17 UTC, cbeauchesne requested changes

2023-09-29 14:17 UTC, cbeauchesne commented on tests/otel_tracing_e2e/test_e2e.py
> +from utils.tools import get_logger, get_rid_from_request
a singleton is available: 

```suggestion
from utils.tools import logger, get_rid_from_request
```

2023-09-29 14:17 UTC, cbeauchesne commented on tests/otel_tracing_e2e/test_e2e.py
> +logger = get_logger()
You can remove this (see above)

2023-09-29 14:17 UTC, cbeauchesne commented on tests/otel_tracing_e2e/test_e2e.py
> +            return
It 'll be the same as simply removing the test. Nobody will never look on this again, as the warning only shows in a log file.

If you want to give it a chance to be a real test on day, it's better to separate in a dedicated test function, and flag it as flaky (we're developping tooling to follow skipped tests).

2023-09-29 14:17 UTC, cbeauchesne commented on tests/otel_tracing_e2e/test_e2e.py
> +        except ValueError:
same comment as above

2023-09-29 14:17 UTC, cbeauchesne commented on tests/otel_tracing_e2e/test_e2e.py
> +        try:
Same comment

2023-10-03 14:03 UTC, songy23 commented
Friendly ping @cbeauchesne

2023-10-03 14:09 UTC, cbeauchesne commented
Ah sorry, I understood from this comment that you'll split tests in two parts, the one validating backend, and the rest : 

> OK, separating the backend validation to another test sounds a better idea.
>
> With this change at least the CI failure indicates the otel tests cannot be built and should be fixed. We ran into similar issues before when breaking changes in this repo broke the otel tests and got ignored.

I misunderstood ?

2023-10-03 14:23 UTC, songy23 commented
> we're developping tooling to follow skipped tests

Sorry maybe I didn't read it correctly but do we already have the tooling in place?

2023-10-03 16:25 UTC, cbeauchesne commented
> Sorry maybe I didn't read it correctly but do we already have the tooling in place?

Yes we have :)

2023-10-03 17:07 UTC, songy23 commented
Currently the OTel E2E tests heavily rely on the backend validation (in fact all validations are on backend data). Changing it will require several weeks' work. In the mean time I'd suggest merging this PR first, otherwise the CI will remain broken. WDYT?

2023-10-04 10:29 UTC, cbeauchesne commented
Up to you, as long as you are ok with the risk of the test being not that useful, all good for me.

2023-10-04 10:29 UTC, cbeauchesne approved these changes

2023-10-04 13:29 UTC, merged