feat: Update OTel span attribute parametric tests
DataDog/system-tests pull request #1656
Opened 2023-10-04 06:57 UTC by PerfectSlayer

## Description

Update the OTel span attributes parametric tests according to the RFC.

## Motivation

The OpenTelemetry API RFC changed the array values encoding for span attributes.

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [x] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

2023-10-04 12:44 UTC, bwoebi commented on tests/parametric/test_otel_span_methods.py
> +            false_string = "false"
Should we distinguish that? At the very least, OTel says that, the json representation of non-string values should be used. That would be just `true` and `false`.

Would also make sense to me to have that uniformly here, given that anything exported by OLTP will also be `true` and `false`, and not `True` and `False`.

2023-10-04 12:55 UTC, cbeauchesne requested changes

2023-10-04 12:55 UTC, cbeauchesne commented on tests/parametric/test_otel_span_methods.py
> +    @missing_feature(context.library == "python-http", reason="Array encoding not implemented")
```suggestion
    @missing_feature(context.library == "python_http", reason="Array encoding not implemented")
```

2023-10-04 16:19 UTC, cbeauchesne reviewed
Failure on python is not related, I'm fixing it in another PR

2023-10-05 10:43 UTC, cbeauchesne approved these changes

2023-10-06 10:36 UTC, merged