fixed wrong asssertion, must set span kind not type
DataDog/system-tests pull request #1796
Opened 2023-11-06 15:59 UTC by dianashevchenko

## Description
Relates to / Noticed in https://github.com/DataDog/dd-trace-go/pull/2334

## Motivation
Previously, we were wrongfully setting span.type based on the span.kind attribute. Now, span.kind will map to span.kind.

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

2023-11-06 16:02 UTC, darccio approved these changes
LGTM 😁

2023-11-07 07:18 UTC, robertomonteromiguel requested changes
There are some failures related with this change

2023-11-07 15:15 UTC, dianashevchenko commented
@robertomonteromiguel since I'm fixing the test itself, it is expected to have some failures. It should pass on Go however, as it is merged already

2023-11-07 19:39 UTC, robertomonteromiguel requested changes

2023-11-07 19:39 UTC, robertomonteromiguel commented on tests/apm_tracing_e2e/test_otel.py
> +        assert child.get("meta").get("span.kind") == "internal"
You should annotate this method with @missing_feature for current golang prod release and for Java (see CI failures).

2023-11-08 11:22 UTC, robertomonteromiguel approved these changes

2023-11-08 11:45 UTC, merged