python: enable support for opentelemetry api
DataDog/system-tests pull request #1847
Opened 2023-11-15 16:12 UTC by majorgreys

## Description

This enables Python support for opentelemetry api tests covering reserved span attributes and operation name.

- https://github.com/DataDog/dd-trace-py/pull/7587
- https://github.com/DataDog/dd-trace-py/pull/7619

## Motivation

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

2023-11-17 07:01 UTC, robertomonteromiguel requested changes
There are tests failures in the CI.
I guess we are waiting for merge dd-trace-py. (if it's the case, it would be better to set the PR in Draft state)

2023-11-17 16:20 UTC, majorgreys commented
@robertomonteromiguel I am not sure if the tests here are run against the default branch of the dd-trace-py repo or the latest released version. Is it the latter?

2023-11-20 08:08 UTC, robertomonteromiguel commented
> @robertomonteromiguel I am not sure if the tests here are run against the default branch of the dd-trace-py repo or the latest released version. Is it the latter?

The tests should be run agains the latest release. 

- https://github.com/DataDog/system-tests/blob/2f3206ecee5bef0f2ee016925b7af910064978c8/tests/parametric/conftest.py#L101
- https://github.com/DataDog/system-tests/blob/main/docs/scenarios/parametric.md#python
- https://github.com/DataDog/system-tests/blob/main/utils/build/docker/python/parametric/ddtracer_version.Dockerfile

2023-11-22 08:56 UTC, robertomonteromiguel approved these changes

2024-09-05 15:58 UTC, cbeauchesne commented
Hi @majorgreys, do you still plan to work on this ?

2024-10-29 16:02 UTC, emmettbutler approved these changes

2024-11-01 18:42 UTC, mabdinur commented on utils/build/docker/python_http/parametric/apm_test_client/server.py
> +    # Python SpanKind enum starts at 0 whereas the proto spec used here starts at 1
This file no longer exists. The python_http app was removed. You should update your branch

2024-11-01 18:42 UTC, mabdinur commented on utils/build/docker/python/parametric/apm_test_client/server.py
> +        span_kind = request.span_kind - 1 if request.span_kind > 0 else 0
Nice catch but I do not like how this argument is defined. `UNSPECIFIED` is not a valid state for SpanKind. According to the spec we should only support internal, server, client, consumer, producer: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind. 

If the SpanKind needs to be "unspecified" then we should change the type of this argument to an Optional[int].

2024-11-04 09:19 UTC, cbeauchesne commented
Setting this PR as draft to destress my notifications list :)

2025-02-05 13:45 UTC, majorgreys commented
@cbeauchesne  @mabdinur I will close this PR as I do not intend to continue it.

2025-02-05 13:45 UTC, closed without merging