[GO]: parametic/ test default propagation style
DataDog/system-tests pull request #1853
Opened 2023-11-16 18:30 UTC by JianyiGao

## Description

This PR test default propagation style for golang. Default style changed from `tracecontext,datadog` to `datadog,tracecontext`
Corresponding change: https://github.com/DataDog/dd-trace-go/pull/2349

## Motivation

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

2023-11-17 07:03 UTC, robertomonteromiguel requested changes
There are tests failures in the CI.
I guess we are waiting for merge dd-trace-go. (if it's the case, it would be better to set the PR in Draft status)

2023-11-20 07:09 UTC, robertomonteromiguel approved these changes

2023-11-28 18:54 UTC, zacharycmontoya approved these changes
I'm not familiar with the go changes, but the test skip changes look good to me

2024-02-05 16:00 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
>      @irrelevant(context.library == "nodejs", reason="library does not implement this default configuration")
```suggestion
    @missing_feature(context.library < "golang@1.61.0", reason="Default value starting on 1.61.0")
    @irrelevant(context.library == "nodejs", reason="library does not implement this default configuration")
```

2024-02-05 16:02 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +    @irrelevant(context.library == "golang", reason="library does not implement this default configuration")
```suggestion
    @irrelevant(context.library >= "golang@1.61.0", reason="Default value was switched to datadog,tracecontext")
```

2024-02-05 19:11 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +    @irrelevant(context.library < "golang@1.61.0.dev", reason="Default value was updated in v1.61 (w3c phase 2)")
```suggestion
    @irrelevant(context.library < "golang@1.62.0", reason="Default value was updated in v1.62.0 (w3c phase 2)")
```

2024-02-05 19:12 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +    @irrelevant(context.library >= "golang@1.61.0.dev", reason="Default value was switched to datadog,tracecontext")
```suggestion
    @irrelevant(context.library >= "golang@1.62.0", reason="Default value was switched to datadog,tracecontext")
```

2024-02-05 21:46 UTC, merged