Update test_telemetry.py after dd-trace-js migrates to telemetry v2
DataDog/system-tests pull request #1918
Opened 2023-12-12 18:51 UTC by ida613

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

2023-12-13 22:24 UTC, iunanua approved these changes

2023-12-14 13:10 UTC, cbeauchesne requested changes

2023-12-14 13:10 UTC, cbeauchesne commented on tests/appsec/waf/test_telemetry.py
> +    elif context.library == "nodejs":
We still test the prod version:

```suggestion
    elif context.library > "nodejs@4.20.0":
```

2023-12-15 16:41 UTC, cbeauchesne approved these changes

2023-12-15 16:42 UTC, merged

2023-12-15 16:42 UTC, cbeauchesne commented
I've merged it, as it makes lot of PR very red.

There is probably another regression in app heartbeat, we'll se later