Support semver version ranges for `released` decorator (and manifests)
DataDog/system-tests pull request #2045
Opened 2024-01-23 15:45 UTC by simon-id

## Motivation

In Node.js we have multiple release lines (ie: v3.x, v4.x, etc...). Historically we would put the latest version in the system-tests manifest, without specifying the potentially backported versions.

Example:
Feature `Test_Blocking_request_cookies` has been released in v3.37.0 and v4.16.0.
Current manifest:
```yaml
Test_Blocking_request_cookies: v4.16.0
```

Ideally we'd want to specify the full compatibility range like this:
```yaml
Test_Blocking_request_cookies: ^3.37.0 || >=4.16.0
```
Where `^3.37.0` is equivalent to `>=3.37.0 <4.0.0`

## Changes

Yeah basically you can do it now, thanks to the pip package `semantic_version` and yours truly.
I kept it compatible with the current `vX.X.X` syntax, so if the version declaration starts with `v`, it will use the classic "above or equal", else it will consider it as a semver spec.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

2024-01-23 15:47 UTC, simon-id commented
I tested all the nominal cases manually and it works perfectly. But I had enough python today to write unit tests for this, please someone from the @DataDog/system-tests-core team take over the PR.

2024-01-30 13:28 UTC, uurien approved these changes

2024-04-04 14:08 UTC, simon-id commented on docs/edit/manifest.md
> +       # the caret character locks the major version
```suggestion
       # the caret character locks the major version (ie: `>=1.3.0 && <2.0.0`)
```

2024-04-05 12:50 UTC, simon-id commented on utils/_decorators.py
> +                if semver.Version(str(tested_version)) in semver.NpmSpec(declaration):
`semver.Version()` will throw if test_version is not a valid semver, should we put a try catch ?

2024-04-12 07:34 UTC, simon-id commented on tests/test_the_test/test_manifest.py
> -test_content()
did you skip the manifest tests ? why

2024-04-12 09:25 UTC, simon-id commented
The 2 python parametric jobs failing are also failing in master :shrug:

2024-04-16 07:57 UTC, smola approved these changes

2024-04-16 09:48 UTC, simon-id commented
@DataDog/system-tests-core

2024-04-16 09:55 UTC, simon-id commented
I am not sure we can easily reconcile this SemVer spec with the manifest schema in `/manifests/parser/schema.json`. Maybe the manifest validation should be done python side instead ?

2024-04-23 16:24 UTC, cbeauchesne commented
`./format.sh` to fis the lint job

2024-04-23 16:26 UTC, cbeauchesne commented on tests/test_the_test/test_manifest.py
> -test_content()
put it back please

2024-04-24 11:47 UTC, cbeauchesne requested changes

2024-04-25 08:49 UTC, cbeauchesne approved these changes

2024-04-25 08:58 UTC, merged