feat: add aws sns context propagation and DSM tests
DataDog/system-tests pull request #2095
Opened 2024-01-31 19:08 UTC by wconti27

## Motivation

More testing

## Changes

Adds AWS SNS Context Propagation Test with SQS as a consumer and DSM Tests. Also adds test application for nodejs

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

2024-02-07 07:05 UTC, robertomonteromiguel requested changes
Minor suggested changes.
Revert the ci.yml change!

2024-02-07 07:05 UTC, robertomonteromiguel commented on tests/integrations/crossed_integrations/test_sns_to_sqs.py
> +#         super().test_consume_trace_equality()
can we remove this?

2024-02-14 18:37 UTC, wconti27 commented on tests/integrations/crossed_integrations/test_sns_to_sqs.py
> +            #     topic = span["meta"]["messaging.url"].split("/")[-1]
Done

2024-02-14 18:37 UTC, wconti27 commented on tests/integrations/crossed_integrations/test_sns_to_sqs.py
> +        """Extracts the queue from a span by trying various fields"""
Fixed

2024-02-14 18:38 UTC, wconti27 commented on .github/workflows/ci.yml
> +          # - macos-latest
Done, sometimes the mac-os tests take upwards of 30 minutes to get a runner and actually run! Much faster to comment it out, then restore later.

2024-02-14 18:39 UTC, wconti27 commented on tests/integrations/crossed_integrations/test_sns_to_sqs.py
> +#         super().test_consume_trace_equality()
done

2024-02-15 15:33 UTC, robertomonteromiguel approved these changes

2024-02-15 15:36 UTC, merged