python: update default headers
DataDog/system-tests pull request #2112
Opened 2024-02-05 17:31 UTC by mabdinur

## Motivation

Fixes failing parametric test: https://github.com/DataDog/system-tests/actions/runs/7787338188/job/21236589128

## Changes

With `ddtrace>=2.6.0` the default tracecontext header will be `datadog,tracecontext`.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

2024-02-05 18:40 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
>      @irrelevant(context.library == "dotnet", reason="library does not implement this default configuration")
```suggestions
    @irrelevant(context.library == "dotnet", reason="library does not implement this default configuration")
    @irrelevant(context.library == "golang", reason="library does not implement this default configuration")
```

2024-02-05 18:40 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +    @irrelevant(context.library >= "python@2.6.0", reason="Default value was switched to datadog,tracecontext")
```suggestion
    @irrelevant(context.library == "golang", reason="library does not implement this default configuration")
    @irrelevant(context.library >= "python@2.6.0", reason="Default value was switched to datadog,tracecontext")
```

2024-02-06 06:54 UTC, robertomonteromiguel requested changes
There are conflicts with the main branch

2024-02-06 15:55 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +    @irrelevant(context.library < "python@2.6.0", reason="Default value was switched to datadog,tracecontext")
```suggestion
    @irrelevant(context.library <= "python@2.5.0", reason="Default value was switched to datadog,tracecontext")
```

2024-02-06 17:31 UTC, cbeauchesne approved these changes

2024-02-07 06:51 UTC, robertomonteromiguel approved these changes

2024-02-07 14:48 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +    @irrelevant(context.library >= "python@2.6.0", reason="Default value was switched to datadog,tracecontext")
```suggestion
    @irrelevant(context.library < "python@2.6.0", reason="Default value was switched to datadog,tracecontext")
```

2024-02-07 14:48 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +    @irrelevant(context.library < "python@2.6.0", reason="Default value was switched to datadog,tracecontext")
```suggestion
    @irrelevant(context.library >= "python@2.6.0", reason="Default value was switched to datadog,tracecontext")
```

2024-02-07 15:51 UTC, merged