deactivate apisec tests for sampling
DataDog/system-tests pull request #2166
Opened 2024-02-20 12:23 UTC by christophe-papazian

## Motivation

Sampling mechanism is currently changing. Previous RFC is deprecated and a new RFC is soon to be approved.

## Changes

deactivate irrelevant test.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

2024-02-20 13:49 UTC, robertomonteromiguel approved these changes
From the point of view of CI and system-tests framework, it's right

2024-02-20 13:53 UTC, robertomonteromiguel requested changes
thinking about it, why don't you use the irrelevant method decorator, specifying the version from which these tests would be irrelevant?

2024-02-20 14:00 UTC, robertomonteromiguel approved these changes

2024-02-20 14:00 UTC, christophe-papazian commented
@simon-id 
For the tests, it's breaking. Otherwise, in a production environment, backend should see more schemas and tracers should compute less schemas. It's a win-win.

2024-02-20 14:50 UTC, simon-id commented
Where is the new test btw ?

2024-02-20 15:43 UTC, christophe-papazian commented
@simon-id Yet to be done.

2024-02-20 15:52 UTC, simon-id commented
Then there is no point in removing coverage until the new test and new implementation is rolled out.

2024-02-21 09:10 UTC, cbeauchesne commented
What about using the legacy trick ? You don't have to touch manifest, and you keep testing libs that have not yet implemented the new behavior

```python
class TestSampling:
    @irrelevant(context.library > "python@1.2", reason="Python implemented the new behavior at v1.2")
    def test_legacy_behavior(self):
         # old stuff

    @irrelevant(context.library <= "python@1.2", reason="Python implemented the new behavior at v1.2")
    @missing_feature(library="java", reason="java still use the old behavior")
    def test_behavior(self):
         # new stuff
```

2024-02-21 10:49 UTC, simon-id commented
@christophe-papazian Disable it for your own library if you want, but I want to keep the coverage on mine, until we implement the new feature and new test, thank you

2024-02-29 08:03 UTC, merged

2024-02-29 10:49 UTC, simon-id commented on tests/appsec/api_security/test_apisec_sampling.py
> +    @irrelevant(True, reason="RFC is deprecated by a newer RFC. New tests will be implemented")
@christophe-papazian i see you've made a commit `do not touch other libs` but doesn't this affect other libs ?