Add ++manifest option to run system-tests from an external manifest
DataDog/system-tests pull request #2342
Opened 2024-04-15 12:13 UTC by vpellan

## Motivation

This was made during the 24q2 k9 innovation week. You can look at the slides at [this link](https://docs.google.com/presentation/d/1Q6UxrBnLsLik_7_-MQoTv8yTy_jYkKAZOfq5yNM5aLA/edit?usp=sharing)

## Changes

This PR adds a ++manifest (or +m) option to run.sh that runs the system-tests using an external manifest

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

2024-04-16 09:00 UTC, cbeauchesne requested changes
Need to be discussed, see my answer on slack.

2024-04-16 09:03 UTC, cbeauchesne reviewed
But without going to far in the discussion, my very first comment is that this PR achieves exactly what `-F <test_path>` does.

If for some reason, `-F <test_path>` is not a good fit, we must remove it. But we can't keep two mechanisms for the same feature.

2024-04-16 12:29 UTC, simon-id commented
100% agree with the comment above

2025-02-03 14:49 UTC, cbeauchesne commented
Seen with Victor, closing this PR, until we find a proper solution

2025-02-03 14:49 UTC, closed without merging