Munir/enable ruby span links tests
DataDog/system-tests pull request #2351
Opened 2024-04-17 03:39 UTC by mabdinur

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

2024-04-19 17:02 UTC, mabdinur commented
Blocked by: https://github.com/DataDog/dd-trace-rb/pull/3596

2024-05-03 17:36 UTC, mabdinur commented on tests/parametric/conftest.py
> +                    for trace in traces:
This change was moved here: https://github.com/DataDog/system-tests/pull/2367

2024-05-06 17:45 UTC, mabdinur commented on tests/parametric/test_otel_span_methods.py
>      @missing_feature(context.library == "nodejs", reason="Not implemented")
```suggestion
    @missing_feature(context.library == "nodejs", reason="Not implemented")
    @missing_feature(context.library < "ruby@2.0.0", reason="Not implemented")
```

2024-05-06 17:45 UTC, mabdinur commented on tests/parametric/test_otel_span_methods.py
>      @missing_feature(context.library == "nodejs", reason="Not implemented")
```suggestion
    @missing_feature(context.library == "nodejs", reason="Not implemented")
    @missing_feature(context.library < "ruby@2.0.0", reason="Not implemented")
```

2024-05-06 17:45 UTC, mabdinur commented on tests/parametric/test_otel_span_methods.py
>      @missing_feature(context.library == "nodejs", reason="Not implemented")
```suggestion
    @missing_feature(context.library == "nodejs", reason="Not implemented")
    @missing_feature(context.library < "ruby@2.0.0", reason="Not implemented")
```

2024-05-06 17:47 UTC, mabdinur commented on utils/parametric/_library_client.py
> +            json={"span_id": span_id, "parent_id": parent_id, "attributes": attributes or {},},
```suggestion
            json={
                "span_id": span_id,
                "parent_id": parent_id,
                "attributes": attributes or {},
                "http_headers": http_headers or [],
            },
```

2024-05-06 21:19 UTC, mabdinur commented on utils/build/docker/ruby/parametric/server.rb
> +    extract_grpc_headers(headers)
```suggestion
    if Datadog::Tracing::Contrib::GRPC.respond_to?(:inject)
      Datadog::Tracing::Contrib::GRPC.inject(Datadog::Tracing.active_trace.to_digest, env)
    else
      Datadog::Tracing::Contrib::GRPC::Distributed::Propagation.new.inject!(Datadog::Tracing.active_trace.to_digest, env)
    end
```

2024-05-07 05:54 UTC, robertomonteromiguel requested changes
Your are not triggering the Test_Span_Links test for current dev version of ruby tracer. Is that what you wanted?

2024-05-07 15:21 UTC, mabdinur commented
> Your are not triggering the Test_Span_Links test for current dev version of ruby tracer. Is that what you wanted?

`Test_Span_Links` is set to a minimum version of `2.0.0` and datadog v2.0.0 has not been released: https://github.com/DataDog/dd-trace-rb/releases this could explain why are not running these tests for the current dev version (dev version is likely v2.0.0some_release_candidate). 

I verified locally that these tests pass but should we hold off on merging this change until 2.0.0 is released?

2024-05-08 05:38 UTC, robertomonteromiguel approved these changes

2024-05-08 05:38 UTC, robertomonteromiguel commented
> > Your are not triggering the Test_Span_Links test for current dev version of ruby tracer. Is that what you wanted?
> 
> `Test_Span_Links` is set to a minimum version of `2.0.0` and datadog v2.0.0 has not been released: https://github.com/DataDog/dd-trace-rb/releases this could explain why are not running these tests for the current dev version (dev version is likely v2.0.0some_release_candidate) OR maybe we introduced a regression in this PR: #2222.
> 
> I verified locally that these tests pass but should we hold off on merging this change until 2.0.0 is released?

It was only for double check....you can merge it

2024-05-10 18:33 UTC, merged