[python] Allow 127.0.0.1 as host for Django
DataDog/system-tests pull request #2390
Opened 2024-04-25 07:02 UTC by smola

## Motivation

Convenience setting to facilitate debugging by allowing requests as 127.0.0.1.

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [x] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [x] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [x] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [x] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-05-03 09:06 UTC, robertomonteromiguel requested changes
There are test failure for Python. might be related with this PR?

2024-05-03 09:30 UTC, cbeauchesne commented
> There are test failure for Python. might be related with this PR?

I think it's unrelated, because it's failing on fastapi, which are not django based.

Though, the error is surprising, the failing scenario  set the WAF timeout to 1 (ms, us?), and fastapi catches the attack, where it shouldn't. Does something changed recently ?

2024-05-07 06:58 UTC, cbeauchesne commented
> Though, the error is surprising, the failing scenario set the WAF timeout to 1 (ms, us?), and fastapi catches the attack, where it shouldn't. Does something changed recently ?

FYI : #2425

2024-05-07 09:37 UTC, robertomonteromiguel approved these changes

2024-05-08 07:39 UTC, juanjux approved these changes

2024-05-08 07:40 UTC, merged