[ASM] Collect headers on user SDK events
DataDog/system-tests pull request #2412
Opened 2024-04-30 08:28 UTC by Anilm3

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-04-30 15:43 UTC, manuel-alvarez-alvarez approved these changes
I'm missing some of the headers from [confluence](https://datadoghq.atlassian.net/wiki/spaces/APS/pages/2186870984/HTTP+header+collection) but looks good to me :smile:

2024-04-30 16:14 UTC, Anilm3 commented
> I'm missing some of the headers from [confluence](https://datadoghq.atlassian.net/wiki/spaces/APS/pages/2186870984/HTTP+header+collection) but looks good to me 😄

Indeed, I decided not to include all headers in this particular test as there are a few of them which aren't supported at all by most of the libraries (some XFF, edge WAF) and I wanted to ensure that the implementation of this feature isn't necessarily subject to exhaustive support of all headers, which should be tested separately.

2024-04-30 16:44 UTC, cbeauchesne requested changes
Just small suggestions. The rest is fine

2024-04-30 16:44 UTC, cbeauchesne commented on tests/appsec/test_automated_login_events.py
> +            for header, _ in self.HEADERS.items():
```suggestion
            for header in self.HEADERS:
```

2024-04-30 16:44 UTC, cbeauchesne commented on tests/appsec/test_automated_login_events.py
> +            for header, _ in self.HEADERS.items():
```suggestion
            for header in self.HEADERS:
```

2024-04-30 16:44 UTC, cbeauchesne commented on tests/appsec/test_automated_login_events.py
> +            for header, _ in self.HEADERS.items():
I guess you are only validating the root span ? 

```suggestion
            if span.get("parent_id") not in (0, None):
                return
                
            for header, _ in self.HEADERS.items():
```

Yes, we miss some helper here...

2024-04-30 16:44 UTC, cbeauchesne commented on tests/appsec/test_automated_login_events.py
> +            for header, _ in self.HEADERS.items():
+ same suggestion as above

2024-04-30 16:44 UTC, cbeauchesne commented on tests/appsec/test_event_tracking.py
> +        def validate_user_login_success_header_collection(span):
Same two suggestions

2024-04-30 16:44 UTC, cbeauchesne commented on tests/appsec/test_event_tracking.py
> +        def validate_user_login_failure_header_collection(span):
Same two suggestions

2024-05-01 08:44 UTC, Anilm3 commented on tests/appsec/test_automated_login_events.py
> +    HEADERS = {
If they were used more widely, this would certainly be the way to go, perhaps once all libraries report all headers we can just move them.

2024-05-01 08:44 UTC, Anilm3 commented on tests/appsec/test_automated_login_events.py
> +            for header, _ in self.HEADERS.items():
Done

2024-05-01 08:44 UTC, Anilm3 commented on tests/appsec/test_automated_login_events.py
> +            for header, _ in self.HEADERS.items():
Done

2024-05-01 08:45 UTC, Anilm3 commented on tests/appsec/test_event_tracking.py
> +        def validate_user_login_failure_header_collection(span):
Done

2024-05-02 07:17 UTC, cbeauchesne approved these changes

2024-05-02 07:32 UTC, merged