parametric: support otel config tests in ruby
DataDog/system-tests pull request #2538
Opened 2024-06-07 20:46 UTC by mabdinur

## Motivation

Enables `Test_Otel_Env_Vars` for ruby tracers.

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-06-07 20:47 UTC, mabdinur commented on utils/build/docker/ruby/parametric/server.rb
> +  # c.diagnostics.debug = true # When tests fail, ensure there's enough data to debug the failure.
Enabling debug logging here interferes with the test. We have to find a workaround for this. Maybe update the test cases?

2024-06-10 13:06 UTC, mabdinur commented on utils/build/docker/ruby/parametric/server.rb
> +  # c.diagnostics.debug = true # When tests fail, ensure there's enough data to debug the failure.
```suggestion
  if ENV['DD_TRACE_DEBUG'].nil?
    # When tests fail, ensure there's enough data to debug the failure.
    # If DD_TRACE_DEBUG is set do not override this configuration.
    c.diagnostics.debug = true
  end
```

2024-06-10 13:09 UTC, mabdinur commented on tests/parametric/test_otel_env_vars.py
> +    @missing_feature(context.library == "ruby", reason="does not support enabling opentelemetry via DD_TRACE_OTEL_ENABLED")
```suggestion
    @missing_feature(
        context.library == "ruby", reason="does not support enabling opentelemetry via DD_TRACE_OTEL_ENABLED"
    )
```

2024-06-10 14:41 UTC, cbeauchesne requested changes
Error in parametric runs in CI

2024-06-10 15:27 UTC, mabdinur commented
> Error in parametric runs in CI

I generated the protos using an incompatible version of grpcio-tools. I will re-generate the protos with the correct version.

2024-06-11 17:47 UTC, mabdinur commented
The failing ruby parametric tests are unrelated and will be resolved in a future PR: [Details](https://github.com/DataDog/system-tests/actions/runs/9453083596/job/26064276490?pr=2538)

2024-06-11 17:50 UTC, mabdinur commented on tests/parametric/test_otel_env_vars.py
> +    @missing_feature(context.library == "ruby", reason="does not support enabling opentelemetry via DD_TRACE_OTEL_ENABLED")
```suggestion
    @missing_feature(
        context.library == "ruby", reason="does not support enabling opentelemetry via DD_TRACE_OTEL_ENABLED"
    )
```

2024-06-12 12:41 UTC, cbeauchesne approved these changes

2024-06-12 13:23 UTC, merged