[go] implement RASP endpoints + enable SSRF
DataDog/system-tests pull request #2551
Opened 2024-06-12 14:33 UTC by eliottness

## Motivation

Support RASP tests

## Changes

Implement rasp endpoints as per spec in `docs/weblog/README.md`

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-06-18 14:09 UTC, eliottness commented on utils/build/docker/golang/app/internal/rasp/rasp.go
> +	_, err = db.Exec("SELECT * FROM users WHERE name = '" + sqli)
```suggestion
	_, err = db.Exec("SELECT * FROM users WHERE name = '" +sqli+"'")
```

2024-06-18 15:48 UTC, Hellzy reviewed
Thanks for this.
Is the go.work.sum supposed to be modified?

2024-06-18 15:48 UTC, Hellzy commented on utils/build/docker/golang/app/internal/rasp/rasp.go
> +		}
Is this really necessary? Can't we leave that to the actual body monitoring tests?

2024-06-18 15:48 UTC, Hellzy commented on utils/build/docker/golang/app/internal/rasp/rasp.go
> +	db, err := sql.Open("sqlite3", ":memory:")
``
```suggestion
        // TODO: use sqltrace pkg once RASP SQLi gets merged in dd-trace-go
	db, err := sql.Open("sqlite3", ":memory:")
```

2024-06-18 15:48 UTC, Hellzy commented on utils/build/docker/golang/app/internal/rasp/rasp.go
> +	_, err := os.ReadFile(path)
```suggestion
        // TODO: use lfitrace (or equivalent) pkg once RASP LFI is implemented and merged in dd-trace-go
	_, err := os.ReadFile(path)
```

2024-06-19 06:51 UTC, robertomonteromiguel requested changes
should we activate the tests related to these endpoint with the manifest file?

2024-06-19 09:19 UTC, eliottness commented
> should we activate the tests related to these endpoint with the manifest file?

@robertomonteromiguel We did and it uncovered a bug so we are doing a patch release 😅

 All 3 endpoints have been tested tho

2024-06-19 09:21 UTC, eliottness commented
> Thanks for this.
> 
> Is the go.work.sum supposed to be modified? 

@Hellzy I guess so because it gets modified along the go.mod file when I upgrade dd-trace-go

2024-06-19 10:59 UTC, robertomonteromiguel approved these changes

2024-06-19 11:00 UTC, merged