[.NET] clean up build scripts
DataDog/system-tests pull request #2606
Opened 2024-06-25 20:54 UTC by lucaspimentel

## Motivation

Trying to make local builds easier for .NET.

## Changes

- move the .NET files so the two projects (`weblog` and `parametric`) are not nested one inside the other
- add `.gitattribute` so keep LF line endings in `*.sh` files even on Windows (removes the need to install and run `dos2unix` tool inside docker images)
- other miscellaneous clean-up (e.g. consolidating env vars)

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-06-26 22:10 UTC, lucaspimentel commented
* **#2610** <a href="https://app.graphite.dev/github/pr/DataDog/system-tests/2610?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2606** <a href="https://app.graphite.dev/github/pr/DataDog/system-tests/2606?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lucaspimentel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-28 01:11 UTC, lucaspimentel commented on .gitignore
> -/utils/build/docker/dotnet/app.csproj.user
[Note to reviewers] These are handled below with `.vs/` and `**/dotnet/**/*.user`.

2024-06-28 01:15 UTC, lucaspimentel commented on tests/parametric/conftest.py
> +RUN apt-get update && apt-get install -y curl binutils
[Note to reviewers]
- removed `dos2unix`, not needed anymore
- add `binutils`, required by `install_ddtrace.sh`
- combined the two packages into one line ([Docker best practice](https://docs.docker.com/build/building/best-practices/#apt-get))

2024-06-28 01:16 UTC, lucaspimentel commented on tests/parametric/conftest.py
> +ENV CORECLR_PROFILER_PATH=/opt/datadog/linux-x64/Datadog.Trace.ClrProfiler.Native.so
TODO: use correct arch from buildx params

2024-06-28 01:18 UTC, lucaspimentel commented on utils/build/docker/dotnet/parametric/Dockerfile
> +ENV CORECLR_PROFILER_PATH=/opt/datadog/linux-x64/Datadog.Trace.ClrProfiler.Native.so
TODO: get correct arch from buildx params

2024-06-28 01:18 UTC, lucaspimentel commented on utils/build/docker/dotnet/install_ddtrace.sh
> +# use 'strings' command from 'binutils' package to extract assembly version
[Note to reviewers] Moved `apt-get install` to Dockerfile so it can be cached in an image layer

2024-06-28 01:18 UTC, lucaspimentel commented on utils/build/docker/dotnet/parametric/ddtracer_version.Dockerfile
> +RUN apt-get update && apt-get install -y binutils
[Note to reviewers]
- removed `dos2unix`, not needed anymore
- add `binutils`, required by `install_ddtrace.sh`

2024-06-28 01:19 UTC, lucaspimentel commented on utils/build/docker/dotnet/poc.Dockerfile
> +RUN apt-get update && apt-get install -y binutils
[Note to reviewers]
- removed `dos2unix`, not needed anymore
- add `binutils`, required by `install_ddtrace.sh`

2024-06-28 18:04 UTC, lucaspimentel commented on utils/scripts/load-binary.sh
> -        ../utils/scripts/docker_base_image.sh ghcr.io/datadog/dd-trace-dotnet/dd-trace-dotnet:latest .
[Note to reviewers] We haven't been using `ghcr.io/datadog/dd-trace-dotnet/dd-trace-dotnet:latest`. It was last updated July 2023.

2024-07-01 06:42 UTC, robertomonteromiguel requested changes
There are failures building the dotnet apps.

2024-07-01 06:42 UTC, robertomonteromiguel commented
I move to draft

2024-07-01 22:59 UTC, lucaspimentel commented on utils/build/docker/dotnet/install_ddtrace.sh
> -apt-get install -y binutils #we need 'strings' command to extract assembly version which is part of binutils package
[Note to reviewers] This `apt-get install -y binutils` was moved to the dockerfile so it's baked into an image layer (and potentially cached).

2024-07-03 06:19 UTC, robertomonteromiguel approved these changes

2024-07-03 08:07 UTC, robertpi approved these changes
Great stuff, thanks for all these efforts!

2024-07-03 12:32 UTC, lucaspimentel commented
### Merge activity

* **Jul 3, 8:32 AM EDT**: @lucaspimentel started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/DataDog/system-tests/2606).

2024-07-03 12:33 UTC, merged