draft: adding otel kafka trace propagation tests
DataDog/system-tests pull request #2620
Opened 2024-06-27 14:10 UTC by wconti27

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-10 05:04 UTC, cbeauchesne commented on .github/actions/pull_images/action.yml
> +        python utils/scripts/get-image-list.py '${{ inputs.scenarios }}' ${{ inputs.exclude_buddies_images }} > compose.yaml
This issue should have been fixed by #2704, let me know if you have trouble with this point.

2024-07-18 08:23 UTC, cbeauchesne requested changes

2024-07-18 08:23 UTC, cbeauchesne commented on utils/scripts/get-image-list.py
> +    exclude_buddies_images = sys.argv[4]
No more a need, the image are built before this step inthe CI

2024-07-22 12:11 UTC, PerfectSlayer approved these changes
Okay for apm-java related changes.

2024-11-04 17:02 UTC, cbeauchesne commented
Hi @wconti27 

Do you still plan to merge this PR ?

2025-02-03 21:03 UTC, closed without merging