switch some weblog images to alpine
DataDog/system-tests pull request #2627
Opened 2024-06-27 17:41 UTC by rochdev

## Motivation

Alpine is a lot smaller which will make pulling the images much faster.

## Changes

Switch weblog images to alpine.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-12 19:57 UTC, Qard approved these changes

2024-07-15 06:40 UTC, robertomonteromiguel requested changes
There are some test failures related with this PR

2024-07-15 12:36 UTC, simon-id commented on utils/build/docker/nodejs_otel/express4-otel.Dockerfile
> +RUN ls -lisa /usr/app/node_modules
new line for debug or forgot to remove ?

2024-07-15 15:14 UTC, rochdev commented
> Yeah that looks like an unrelated problem actually, no idea why standalone appsec tests would fail only on alpine

@simon-id I rebased and it's still failing, but it's not failing on `main`. For some reason locally for me it fails on every branch, but in CI it's only in this branch which seems to indicate some problem between AppSec and Alpine.

2024-07-15 16:29 UTC, simon-id approved these changes

2024-07-15 18:12 UTC, rochdev commented
@robertomonteromiguel Everything is passing now.

2024-07-16 07:13 UTC, robertomonteromiguel approved these changes

2024-07-16 13:34 UTC, merged