[.NET] skip flaky test `test_otel_get_span_context` for now
DataDog/system-tests pull request #2665
Opened 2024-07-03 13:43 UTC by lucaspimentel

## Motivation

It's flaky.

Tests should not use `traces[0]` to get the "first" span, since the order of spans is not guaranteed.

## Changes

Skip it.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-03 13:44 UTC, andrewlock approved these changes

2024-07-03 13:45 UTC, andrewlock commented on tests/parametric/test_otel_span_methods.py
> +    @bug(context.library == "dotnet", reason="Flaky due to span order, tests should never use traces[0] when there are multiple spans")
```suggestion
    @bug(
        context.library == "dotnet",
        reason="Flaky due to span order, tests should never use traces[0] when there are multiple spans",
    )
```

2024-07-03 13:50 UTC, lucaspimentel commented on tests/parametric/test_otel_span_methods.py
> +    @bug(context.library == "dotnet", reason="Flaky due to span order, tests should never use traces[0] when there are multiple spans")
Fixed, thanks!

2024-07-03 14:41 UTC, robertomonteromiguel requested changes
why no use the flaky decorator?

2024-07-03 14:42 UTC, lucaspimentel commented
> why no use the flaky decorator?

I didn't know that was a thing, thanks!

2024-07-03 14:46 UTC, lucaspimentel commented
> why no use the flaky decorator?

What's the synax? I tried `@flaky` [as documented](https://github.com/DataDog/system-tests/blob/main/docs/edit/features.md#skip-tests) and got this error: 

```
___________________________________________________ ERROR collecting tests/parametric/test_otel_span_methods.py ____________________________________________________
tests\parametric\test_otel_span_methods.py:28: in <module>
    class Test_Otel_Span_Methods:
tests\parametric\test_otel_span_methods.py:400: in Test_Otel_Span_Methods
    @flaky(
E   NameError: name 'flaky' is not defined
```

2024-07-03 14:50 UTC, robertomonteromiguel commented
> > why no use the flaky decorator?
> 
> What's the synax? I tried `@flaky` [as documented](https://github.com/DataDog/system-tests/blob/main/docs/edit/features.md#skip-tests) and got this error:
> 
> ```
> ___________________________________________________ ERROR collecting tests/parametric/test_otel_span_methods.py ____________________________________________________
> tests\parametric\test_otel_span_methods.py:28: in <module>
>     class Test_Otel_Span_Methods:
> tests\parametric\test_otel_span_methods.py:400: in Test_Otel_Span_Methods
>     @flaky(
> E   NameError: name 'flaky' is not defined
> ```

You need to import it. The syntax is the same as "bug"

2024-07-03 14:51 UTC, robertomonteromiguel commented
> > > why no use the flaky decorator?
> > 
> > 
> > What's the synax? I tried `@flaky` [as documented](https://github.com/DataDog/system-tests/blob/main/docs/edit/features.md#skip-tests) and got this error:
> > ```
> > ___________________________________________________ ERROR collecting tests/parametric/test_otel_span_methods.py ____________________________________________________
> > tests\parametric\test_otel_span_methods.py:28: in <module>
> >     class Test_Otel_Span_Methods:
> > tests\parametric\test_otel_span_methods.py:400: in Test_Otel_Span_Methods
> >     @flaky(
> > E   NameError: name 'flaky' is not defined
> > ```
> 
> You need to import it. The syntax is the same as "bug"

https://github.com/DataDog/system-tests/blob/b13f7317e1ed34a4b2579b2a9bb34007578bd078/utils/_decorators.py#L142

2024-07-03 16:00 UTC, lucaspimentel commented
@robertomonteromiguel, fixed. Thank you!

2024-07-04 06:00 UTC, robertomonteromiguel approved these changes

2024-07-04 06:01 UTC, merged

2024-07-04 06:01 UTC, lucaspimentel commented
### Merge activity

* **Jul 4, 2:01 AM EDT**: @lucaspimentel merged this pull request with [Graphite](https://app.graphite.dev/github/pr/DataDog/system-tests/2665).