make disk cleanup optional when pulling images
DataDog/system-tests pull request #2720
Opened 2024-07-10 17:54 UTC by rochdev

## Motivation

The cleanup step takes most of the time of the job and is not needed when using larger runners which have more disk space ([600GB](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#specifications-for-general-larger-runners) vs [14GB](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)).

With the cleanup, the `pull_images` job takes 5-15 minutes for `INTEGRATIONS`. Without the cleanup, it takes ~30 seconds.

## Changes

Make disk cleanup optional when pulling images.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-11 11:51 UTC, cbeauchesne requested changes
with the default value set to true, it'll be uses on this present CI, which cannot be made with a little bit more visibility : 

* either we continue using default runner => get the current left space at the end of end-to-end process for all weblogs, to see if we are close to the limit or not
* or we use large runner => what are the avaibility of those large runner ? we spawn thousand of jobs every day, and we already have some wait time for a runner to be present. We must not loose here what we gain by removing the `rm`. And I also don't want to exhaust the DD large runners grid, just to save 2mn of CI time.

Another easy solution is to set the default value to `False`, or to add `cleanup=False` in this CI.

But, actually, I'd see a better solution :  be to just get the free space on the disk, and if it's above a limit (let says 20Gb), run the cleanup : 

- no downside
- no new inputs
- no cognitive effort for user 

WDYT ?

2024-07-11 15:35 UTC, rochdev commented
> with the default value set to true, it'll be uses on this present CI, which cannot be made with a little bit more visibility

It's the reverse. A value of `true` is equivalent to today's behaviour, so there won't be any change on the current CI. It has to be set to `false` to trigger the change.

> But, actually, I'd see a better solution : be to just get the free space on the disk, and if it's above a limit (let says 20Gb), run the cleanup :

I prefer to be explicit, otherwise builds won't be deterministic as GitHub only guarantees a _minimum_ size, meaning that a rerun could get a machine with more or less disk space.

2024-07-12 08:39 UTC, cbeauchesne commented
But it's currently not executed ? -> https://github.com/DataDog/system-tests/actions/runs/9880334639/job/27336822494?pr=2720

Or did I missed something ? 

I prefer to be explicit, otherwise builds won't be deterministic as GitHub only guarantees a minimum size, meaning that a rerun could get a machine with more or less disk space.

Agree

2024-07-12 11:14 UTC, rochdev commented
> But it's currently not executed ?

Hmm let me look into it. Originally the condition didn't work so I changed it and assumed it was now working, but it may still be broken in the other way where it just never runs regardless of the config.

2024-07-12 11:32 UTC, rochdev commented
Looks like default values are only supported for strings. I can either switch to a string or change the name to something like `skip-cleanup` which will then automatically default to `false` without having to be explicit.

2024-07-12 16:58 UTC, cbeauchesne approved these changes

2024-07-12 17:42 UTC, merged