parametric(otel); enable ruby span events tests
DataDog/system-tests pull request #2735
Opened 2024-07-12 01:26 UTC by mabdinur

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-12 14:22 UTC, mabdinur commented on tests/parametric/test_otel_span_methods.py
> +    @missing_feature(context.library < "ruby@2.1.0", reason="Not implemented")
```suggestion
    @missing_feature(context.library < "ruby@2.2.0", reason="Not implemented")
```

2024-07-19 06:27 UTC, robertomonteromiguel requested changes
There is a failure on Java Parametric, just in the file "test_otel_span_methods.py".
`FAILED tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods::test_otel_span_started_with_link_from_w3c_headers[library_env0]`
I guess the error it's not related with your changes, but can you confirm this before merge the PR?

2024-07-19 14:28 UTC, zacharycmontoya commented
> There is a failure on Java Parametric, just in the file "test_otel_span_methods.py". `FAILED tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods::test_otel_span_started_with_link_from_w3c_headers[library_env0]` I guess the error it's not related with your changes, but can you confirm this before merge the PR?

I looked into this and it looks like a transient issue with the gRPC connection to the parametric test app:
```
debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-07-18T18:12:13.16942889+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:51003: recvmsg:Connection reset by peer"}"
```

2024-07-19 15:04 UTC, zacharycmontoya approved these changes

2024-07-25 07:55 UTC, cbeauchesne approved these changes

2024-07-26 05:50 UTC, merged