[java] Fix wrong version schema in header related tests
DataDog/system-tests pull request #2740
Opened 2024-07-12 10:57 UTC by manuel-alvarez-alvarez

## Motivation

The version was badly formatted causing the test to XPASS instead of PASS

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-12 11:07 UTC, smola approved these changes

2024-07-12 11:51 UTC, cbeauchesne requested changes
I'm surprised that's even possible, the check should have caught this.

Back on the PR, it also make some test failing.

2024-07-12 14:35 UTC, manuel-alvarez-alvarez commented on manifests/java.yml
> +    Test_HeaderTags: missing_feature
This one still fails, so I moved it back to missing features.

2024-07-12 14:35 UTC, manuel-alvarez-alvarez commented
> I'm surprised that's even possible, the check should have caught this.
> 
> Back on the PR, it also make some test failing.

Yes, thanks for the feedback, I've fixed the failing tests

2024-07-15 14:43 UTC, cbeauchesne approved these changes

2024-07-15 14:51 UTC, merged