[nodejs] enable tags test for node
DataDog/system-tests pull request #2744
Opened 2024-07-12 14:07 UTC by ida613

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-12 20:12 UTC, Qard approved these changes

2024-07-15 05:41 UTC, robertomonteromiguel requested changes
There are test failures related with this change

2024-07-15 09:54 UTC, simon-id commented on utils/build/docker/nodejs/parametric/server.js
> +  for (const [key, value] of request.span_tags) tags[key] = value
```suggestion
  Object.assign(tags, request.span_tags)
```

2024-07-15 09:55 UTC, simon-id commented on utils/build/docker/nodejs/parametric/server.js
> +    tags: tags
```suggestion
    tags
```

2024-07-15 09:56 UTC, simon-id commented on tests/parametric/test_dynamic_configuration.py
> -    @missing_feature(library="nodejs")
please use the version filters like the other PRs

2024-07-15 09:57 UTC, simon-id commented on tests/parametric/test_dynamic_configuration.py
> -    @missing_feature(library="nodejs")
refresher:
```python
@missing_feature(context.library < "nodejs@x.x.x")
```

2024-07-15 14:11 UTC, robertomonteromiguel approved these changes

2024-07-15 17:36 UTC, merged