Fix xpassed Login events tests for java
DataDog/system-tests pull request #2754
Opened 2024-07-15 14:37 UTC by jandro996

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-15 14:43 UTC, jandro996 commented on tests/appsec/test_automated_login_events.py
>  def assert_priority(span, meta):
We need to check if this assert is needed and if it's correct. As far as I know (at least in java) set the manual.keep tag is not propagated to agent and when is set to true sampling priority is set to 2.

2024-07-22 10:58 UTC, cbeauchesne approved these changes
From framework usage, all good.

But I'll be more confortable if you get a review with somebody confortable with the RFC.

2024-07-23 15:08 UTC, manuel-alvarez-alvarez approved these changes

2024-07-24 14:44 UTC, cbeauchesne reviewed
We'll wait for #2810 to re-run the CI

2024-07-25 07:57 UTC, cbeauchesne requested changes
You have a CI failure, but it's probably an issue in the weblog implem : 

https://github.com/DataDog/system-tests/actions/runs/10079723533/job/27867983375?pr=2754#step:12:225

2024-07-25 12:47 UTC, cbeauchesne commented
I rebased your branch, there were an error on `main` ...

2024-07-25 14:38 UTC, cbeauchesne requested changes
Still an error on `spring-boot-openliberty`

https://github.com/DataDog/system-tests/actions/runs/10094392741/job/27912439438?pr=2754#step:12:246

2024-07-26 05:50 UTC, jandro996 commented
Thanks for your comments @cbeauchesne! as you mentioned, we are having issues with `spring-boot-openliberty` so i won't enable it in this iteration

2024-07-29 07:32 UTC, daniel-romano-DD approved these changes

2024-08-06 08:00 UTC, smola approved these changes

2024-08-07 12:26 UTC, cbeauchesne approved these changes

2024-08-07 12:31 UTC, merged