enable easy win tests for API features
DataDog/system-tests pull request #2756
Opened 2024-07-15 20:47 UTC by rachelyangdog

## Motivation

https://datadoghq.atlassian.net/browse/APMAPI-142

## Changes

Deleted bug markers in test test files where the bugs mentioned were no longer relevant. 
Tests previously marked to pass unexpectedly (XPASS) due to bugs were reviewed and the lines causing XPASS were removed after confirming the issues were resolved or irrelevant

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-16 08:41 UTC, cbeauchesne requested changes
CI is failing

2024-07-16 15:08 UTC, rachelyangdog reviewed
Added back the `@bug` for agent version

2024-07-17 08:55 UTC, cbeauchesne approved these changes

2024-07-17 12:45 UTC, lucaspimentel approved these changes

2024-07-17 15:07 UTC, ZStriker19 approved these changes

2024-07-17 17:08 UTC, merged