pin otel api in parametric tests
DataDog/system-tests pull request #2820
Opened 2024-07-25 17:24 UTC by mabdinur

## Motivation

Opentelemetry-api v1.26.0 was released this morning: https://pypi.org/project/opentelemetry-api/#history. This broke ddtrace-opentelemetry support. 

Resolves incompatibility introduced by: open-telemetry/opentelemetry-python@d4e13bd by pinning the package version.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-26 14:26 UTC, zacharycmontoya approved these changes
LGTM, thanks for a quick fix that unblocks our tests

2024-07-26 15:52 UTC, khanayan123 approved these changes

2024-08-05 13:13 UTC, mabdinur reviewed
Fix was released

2024-08-05 13:13 UTC, mabdinur commented on utils/build/docker/python/install_ddtrace.sh
> +
```suggestion
```

2024-08-05 15:30 UTC, cbeauchesne requested changes
CI is happy -> I'm happy :) 

Though, there is a conflict to resolve.

2024-08-05 20:22 UTC, mabdinur commented on tests/parametric/test_otel_span_methods.py
> +    )
```suggestion
```

2024-08-06 08:58 UTC, cbeauchesne approved these changes

2024-08-07 14:28 UTC, merged