[ruby] Add GraphQL threats protection test app and changed blocking tests behaviours for Ruby
DataDog/system-tests pull request #2828
Opened 2024-07-29 11:17 UTC by vpellan

## Motivation

We will release GraphQL Threats Protection for Ruby in the next few weeks

## Changes

Added a test app that contains GraphQL-ruby and a GraphQL schema to test GraphQL threats protection.
Only Ruby should be affected by the changes, but I've deleted "block-all-resolvers" check as it was wrong (Not present in the ruleset, using graphql.server.all_resolvers address would still result in getting the block-resolvers rule triggered.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-07-29 14:11 UTC, pawelchcki commented on utils/build/docker/ruby/graphql23/config/initializers/content_security_policy.rb
> +# Be sure to restart your server when you modify this file.
Small nit.
If this file is not necessary for the Rails app to work, can we remove it ?

2024-07-29 14:17 UTC, pawelchcki commented on utils/build/docker/ruby/graphql23/config/initializers/inflections.rb
> +# Be sure to restart your server when you modify this file.
Small nit.
If this file is not necessary for the Rails app to work, can we remove it ?

2024-07-29 14:18 UTC, pawelchcki commented on utils/build/docker/ruby/graphql23/config/initializers/permissions_policy.rb
> +# Define an application-wide HTTP permissions policy. For further
same as above
If this file is not necessary for the Rails app to work, can we remove it ?

2024-07-29 14:19 UTC, pawelchcki commented on utils/build/docker/ruby/graphql23/Gemfile
> +gem "rdkafka"
lets remove any unused dependences to speed up the installation

2024-07-29 14:21 UTC, pawelchcki requested changes
A few small nits - to remove unnecessary dependencies and files. 
Otherwise LGTM

2024-07-30 07:54 UTC, vpellan commented
Hello @pawelchcki I applied your suggestions. Something to note is that I used Rails 7.1 test app as a base for this one. I previously tried to remove system_test_controller as the tests are using graphql_controller but it crashed the app, which is why I left most of the files as-is. Nevertheless, thanks for your suggestions !

2024-08-01 09:05 UTC, hoolioh approved these changes

2024-08-01 09:05 UTC, hoolioh commented on tests/appsec/test_blocking_addresses.py
> +                ["getUserByName", "0", "name"]
I'd add a comment clarifying why the key_path is different so next implementaters know about this. In order to solve this on the long run and get consistent results we might discuss about modifying the RFC to redefine the WAF's payload format. Other than that LGTM.

2024-08-01 13:06 UTC, merged