Add test section for OTLP Log ingestion in backend
DataDog/system-tests pull request #2914
Opened 2024-08-26 03:43 UTC by IbraheemA

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-08-26 07:27 UTC, cbeauchesne requested changes
The lint fails. Just execute `./format.sh` and all should be good.

2024-08-26 07:28 UTC, cbeauchesne commented
Changing to draft, you can set it back to normal once you need a review from us.

2024-08-26 14:28 UTC, songy23 commented on tests/otel_tracing_e2e/test_e2e.py
> +            log_agent = interfaces.backend.get_logs(
```suggestion
            log_intake = interfaces.backend.get_logs(
```

2024-08-26 14:28 UTC, songy23 commented on tests/otel_tracing_e2e/test_e2e.py
> +            log_agent = interfaces.backend.get_logs(
Same for all reference below

2024-08-26 14:28 UTC, songy23 commented on tests/otel_tracing_e2e/test_e2e.py
> +            otel_log_trace_attrs = validate_log(log_agent, rid, "datadog_agent")
Replace `datadog_agent` with the log source in the endpoint

2024-08-26 14:28 UTC, songy23 commented on tests/otel_tracing_e2e/test_e2e.py
> +            trace_agent = interfaces.backend.assert_otlp_trace_exist(
```suggestion
            trace_intake = interfaces.backend.assert_otlp_trace_exist(
```

2024-08-26 14:28 UTC, songy23 commented on tests/otel_tracing_e2e/test_e2e.py
> +        validate_log_trace_correlation(otel_log_trace_attrs, trace_agent)
```suggestion
        validate_log_trace_correlation(otel_log_trace_attrs, trace_intake)
```

2024-09-25 21:14 UTC, songy23 approved these changes

2024-09-25 21:14 UTC, songy23 commented on utils/otel_validators/validator_log.py
> +import pprint
Where is this used?

2024-09-26 09:06 UTC, cbeauchesne requested changes
Just remove the pprint if not used

2024-09-26 14:43 UTC, IbraheemA commented
/merge

2024-09-27 09:02 UTC, cbeauchesne approved these changes

2024-09-27 12:34 UTC, IbraheemA commented
/merge

2024-09-27 12:38 UTC, merged