[java][wip] enable RASP tests
DataDog/system-tests pull request #2927
Opened 2024-08-27 10:14 UTC by smola

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-08-27 10:15 UTC, jandro996 approved these changes

2024-08-27 10:20 UTC, jandro996 requested changes
Just to review logs, we do not intend for it to be merged

2024-08-29 07:19 UTC, smola commented
Updated the PR, actually meant for merge now (after changing minimum version).

2024-08-29 08:33 UTC, manuel-alvarez-alvarez approved these changes

2024-08-29 09:59 UTC, jandro996 approved these changes
LGTM! although I'm not sure if the bug in payara is on the test or the tracer :)

2024-08-29 10:50 UTC, merged