[Java] SSRF tests for Java (Springboot)
DataDog/system-tests pull request #2949
Opened 2024-08-29 15:23 UTC by ValentinZakharov

## Motivation
We need enabled all Exploit prevention tests

## Changes
Missing RRASP SSRF tests for Java in Springboot

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-08-29 15:43 UTC, robertomonteromiguel requested changes
There are failures on the CI
"AssertionError: In java manifest, class * is declared in tests/appsec/rasp/test_ssrf.py, but does not exists"

2024-08-29 16:07 UTC, smola requested changes

2024-08-29 16:07 UTC, smola commented on manifests/java.yml
> +          '*': irrelevant
```suggestion
          '*': missing_feature (missing endpoint)
```

Let's not use `irrelevant`, since that will skip the test.

2024-08-30 07:58 UTC, smola commented on utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rasp/RaspController.java
> +    @RequestMapping(value = "/ssrf", method = {GET, POST})
Can we exclude weblogs from code vulnerability scanning? Many of these are intentionally insecure, nothing to fix here.

2024-09-04 10:08 UTC, smola approved these changes

2024-09-05 22:10 UTC, closed without merging