Add LFI endpoint for php
DataDog/system-tests pull request #2966
Opened 2024-09-03 15:39 UTC by estringana

## Motivation

LFI endpoint on PHP was empty. This PR implements the expected behaviour of this endpoint. It also enables all lfi tests.

APPSEC-52934

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-09-16 11:57 UTC, cbeauchesne requested changes
CI is failing

2025-01-30 11:42 UTC, estringana commented
@cbeauchesne ci is working now

2025-01-30 12:33 UTC, robertpi commented on tests/appsec/rasp/test_lfi.py
> +from utils import features, weblog, interfaces, scenarios, rfc, bug
minor: don't see why bug is needed here?

2025-01-30 13:37 UTC, estringana commented on tests/appsec/rasp/test_lfi.py
> +from utils import features, weblog, interfaces, scenarios, rfc, bug
Not needed. I will delete it now. Thanks

2025-01-30 16:04 UTC, cbeauchesne approved these changes

2025-01-31 07:08 UTC, merged