feat(iast): path parameter tests
DataDog/system-tests pull request #2972
Opened 2024-09-04 11:35 UTC by avara1986

## Motivation
- Add a new IAST test: path parameter
- Add path parameter tests for Python
- Add `missing_feature` tags for path parameter tests in Java, .NET, Node, etc.

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-09-04 15:20 UTC, smola commented on tests/appsec/iast/source/test_path_parameter.py
> +        super().test_telemetry_metric_instrumented_source()
```suggestion

```

You don't need this method override unless you have to add a decorator. Tests are just run from BaseSourceTest.

2024-09-04 15:20 UTC, smola commented on tests/appsec/iast/source/test_path_parameter.py
> +from utils import features, missing_feature
```suggestion
```

Unused.

2024-09-05 09:01 UTC, cbeauchesne requested changes
good old `./format.sh`

2024-09-05 14:12 UTC, smola approved these changes
Looks good to me.

2024-09-06 08:45 UTC, cbeauchesne approved these changes

2024-09-06 10:59 UTC, merged