Ruby:Update manifest for RC tests
DataDog/system-tests pull request #3011
Opened 2024-09-10 22:46 UTC by marcotc

This PR enables enables previously skipped dynamic configuration, which are going to be fixed in the Ruby tracer 2.3.0, due to missing capabilities being reported (fixed in https://github.com/DataDog/dd-trace-rb/pull/3888).

Also, this PR enables few `XPASS` tests for dynamic configuration.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-09-11 05:38 UTC, robertomonteromiguel requested changes
There are test failures related with this PR

2024-09-11 05:38 UTC, robertomonteromiguel commented on tests/parametric/test_dynamic_configuration.py
> +    @bug(library="ruby")
reason?

2024-09-17 17:17 UTC, rachelyangdog approved these changes

2024-09-18 09:07 UTC, cbeauchesne requested changes

2024-09-18 09:07 UTC, cbeauchesne commented on tests/parametric/test_dynamic_configuration.py
> +    @bug(library="ruby", reason="Telemetry event 'app-client-configuration-change' not found")
Can you set a JIRA ticket as reason for all `bug` declaration (see https://dd.slack.com/archives/C025TJ4RZ8X/p1726490527322989)

2025-02-03 14:56 UTC, cbeauchesne commented
Hi @marcotc ,

Is this PR still needed ?

2025-02-04 22:24 UTC, marcotc commented
I don't remember the context for this PR, and I can't answer the questions without starting it from scratch, so I'll close it.

2025-02-04 22:24 UTC, closed without merging