config_consistency: test ClientIPHeader
DataDog/system-tests pull request #3045
Opened 2024-09-16 14:16 UTC by mabdinur

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-09-18 02:38 UTC, mabdinur commented on tests/test_config_consistency.py
> -def _get_span(spans, resource_name, tags):
@zacharycmontoya I replaced `_get_span` with `_get_span_by_tags`. I found that this approach works best with most libraries. Resource names are not set in a consistent way across client libraries. This is something we can work with IDM to address.

2024-09-18 03:28 UTC, mabdinur commented on utils/_context/_scenarios/__init__.py
> +            # disable ASM to test non asm client ip tagging
```suggestion
            # disable ASM to test http.client _p collection via tracing integrations
```

2024-09-18 09:12 UTC, cbeauchesne requested changes
Just a small typo.

2024-09-18 09:12 UTC, cbeauchesne commented on manifests/php.yml
> +    Test_Config_ClientIPHeader_Configured: v1.3,0
```suggestion
    Test_Config_ClientIPHeader_Configured: v1.3.0
```

2024-09-18 21:36 UTC, cbeauchesne approved these changes

2024-09-19 09:18 UTC, simon-id commented on manifests/nodejs.yml
> +    Test_Config_ClientIPHeader_Configured: *ref_5_15_0
What is this version number coming from ?

2024-09-19 12:29 UTC, mabdinur commented on manifests/nodejs.yml
> +    Test_Config_ClientIPHeader_Configured: *ref_5_15_0
```suggestion    Test_Config_ClientIPHeader_Configured: v5.22.0
```

2024-09-19 12:36 UTC, mabdinur commented on manifests/nodejs.yml
> +    Test_Config_ClientIPHeader_Precedence: missing_feature (all headers listed in the RFC are not supported)
```suggestion
    Test_Config_ClientIPHeader_Configured: v5.22.0
    Test_Config_ClientIPHeader_Precedence: missing_feature (all headers listed in the RFC are not supported)
```

2024-09-19 14:44 UTC, mabdinur commented
CI failures are unreleated (ex: due to mysql issues)

2024-09-19 14:45 UTC, merged

2024-09-19 15:14 UTC, simon-id commented on manifests/nodejs.yml
> +    Test_Config_ClientIPHeader_Configured: *ref_5_15_0
Please don't do that, I've been working hard to not do that for years

2024-09-19 15:14 UTC, simon-id commented on manifests/nodejs.yml
> +    Test_Config_ClientIPHeader_Configured: *ref_5_15_0
Either leave it missing_feature, or ask us to find the correct version