[java] Enabled Java profiling for native-image binaries (tracing shared container)
DataDog/system-tests pull request #3086
Opened 2024-09-20 16:20 UTC by MattAlp

## Motivation

There is no E2E testing for the recently-added native-image-mode Java profiler.
## Changes

This modifies the `spring-boot-3-native` container (note- used by trace scenarios as well) to bake in and enable the Java profiler, as well as enabling the profiling scenarios for this container for `dd-trace-java v1.39.0+`.

It may be more correct to create two separate environments- one with the profiler enabled and one without, to test tracing and profiling functionality separately with different generated binaries.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-09-23 06:10 UTC, robertomonteromiguel requested changes
Is there any assertion for profiling?

2024-09-23 06:10 UTC, robertomonteromiguel commented on utils/build/docker/java/spring-boot-3-native/pom.xml
> +                        -J-javaagent:${agent.path} -J-Ddd.profiling.enabled=true --enable-monitoring=jfr
Do we really want to activate profiling all the time, and could it impact other scenarios?

2024-09-24 06:17 UTC, robertomonteromiguel requested changes
I'm not sure if I would advocate this strategy. We are launching the build twice, every time, whether we run this scenario or not. Looking at the times, it used to take 3 minutes to build this weblog, now it takes 6. What do you think @cbeauchesne?

2024-09-24 12:33 UTC, cbeauchesne commented
Well, the issue here is that we can't activate profiling at run time, it must be done at build time.

As these two steps are totally separated in system tests, there is not good solution.

1. Either we do a totally separated weblog, call `java-native-profiling`, with sole purpose of being tested on the PROFILING scenario
  * pro : in theory, does not add extra time, as it runs it parallel
  * con : CI cost
2. or we build a second jar with profiling  activated, and we use it at runtime based on the value of the env var
  * pro : totally transparant in the system-tests model
  * con : +3 mn in build time

Well, it's not like the native weblog is fast. `2.` is not perfect, but I'm in favor of that compromise.

Do you know if we could run the compilation in two parallel process to leverage the fact we have multiple core on all our machine ? 

```
RUN /opt/apache-maven-3.8.6/bin/mvn -Pnative,with-profiling native:compile && /opt/apache-maven-3.8.6/bin/mvn -Pnative,without-profiling native:compile
```

2024-09-24 12:35 UTC, cbeauchesne commented
> If a container can be built in a different way based on the associated scenario, we can avoid doing the unnecessary compilation.

We could imagine that, by adding an argument to `build.sh`. But as it's the only use case, I prefer to not open this pandora box 😄

2024-09-24 13:31 UTC, robertomonteromiguel approved these changes

2024-09-24 14:10 UTC, merged