baggage system tests
DataDog/system-tests pull request #3101
Opened 2024-09-23 18:33 UTC by rachelyangdog

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-09-27 20:22 UTC, ida613 commented on tests/parametric/test_headers_baggage.py
> +        assert "x-datadog-trace-id" not in headers.keys()
`x-datadog-trace-id` and `x-datadog-parent-id` are required span context fields in nodejs, so not setting them would create an error. I can add a skip flag for node

2024-10-01 20:55 UTC, rachelyangdog commented on tests/parametric/test_headers_baggage.py
> +        """Ensure that only baggage headers are injected when baggage is the only enabled propagation style."""
I think it can occur. In the RFC, it says that users can disable trace context propagation and enable only the baggage propagator...

2024-10-04 09:58 UTC, cbeauchesne requested changes
Just a small detail

2024-10-04 09:58 UTC, cbeauchesne commented on tests/parametric/test_headers_baggage.py
> +import logging
Can you rather use `from utils.tools import logger` ?

2024-10-04 10:08 UTC, PerfectSlayer commented on utils/parametric/_library_client.py
> +    def span_set_baggage(self, span_id: int, key: str, value: str) -> None:
Why is there a `span_id` while baggage API is independent of span / tracing API?

2024-10-07 14:03 UTC, cbeauchesne approved these changes

2024-10-07 16:33 UTC, merged