add older debian tests
DataDog/system-tests pull request #3172
Opened 2024-10-03 16:10 UTC by emmettbutler

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-10-15 10:45 UTC, robertomonteromiguel requested changes
I tried in GitLab and it's failing because a timeout.
It's trying to generate the AMI, and executing the test for all other "not default" vms.
To test this, I advocate adding the `"--vm-only-branch debian"` in the gitlab ci (job onboarding_install_extra_vms). Run the tests with this change, and then remove the change before merge

2024-11-11 21:08 UTC, emmettbutler commented
@robertomonteromiguel this actually passes on my local

2024-11-12 07:15 UTC, robertomonteromiguel requested changes
This PR is in conflict with main branch.
For example you are adding java provisions that have been removed two weeks ago.
I encourage you to do the complete execution of the pipeline.
I use to trick the gitlab.yml by adding the parameter “--vm-only-branch debian”. After I do the full pipeline run and see that the new machines don't fail, I remove these changes before merge

2024-11-13 07:21 UTC, robertomonteromiguel requested changes
There are failures on the CI. Java:

```  The following packages have unmet dependencies:
     default-jdk : Depends: default-jre (= 2:1.21-76) but it is not going to be installed
                   Depends: openjdk-21-jdk but it is not going to be installed
     libc6 : Breaks: chrony (< 4.2-3~) but 3.4-4+deb10u2 is to be installed
    E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.```

2024-11-13 07:21 UTC, robertomonteromiguel commented on utils/_context/virtual_machines.py
> +            aws_config=_AWSConfig(ami_id="ami-0607e701db389efe7", ami_instance_type="t2.medium", user="admin"),
Change the instance type to t3.medium

2024-11-13 07:21 UTC, robertomonteromiguel commented on utils/_context/virtual_machines.py
> +            aws_config=_AWSConfig(ami_id="ami-01055bb8b97dfc981", ami_instance_type="t4g.small", user="admin"),
Change the instance type to t4g.medium

2024-11-13 07:21 UTC, robertomonteromiguel commented on utils/build/virtual_machine/provisions/auto-inject/docker/auto-inject_prepare_docker.yml
> +        sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m) -o /usr/bin/docker-compose && sudo chmod +x /usr/bin/docker-compose && sudo docker-com
we need to check if this change impacts on other machines

2024-11-13 07:21 UTC, robertomonteromiguel commented on utils/build/virtual_machine/weblogs/java/provision_test-app-java-multialpine.yml
> +          sudo apt -y install openjdk-8-jdk-headless openjdk-8-jre-headless
if we are installing the jdk, we shoudn't need the jre

2024-11-15 20:41 UTC, emmettbutler commented
@natitsechanski @robertomonteromiguel I'm having a really tough time debugging the Java errors here. Beyond that, since there are some expected-failing tests, it's not clear to me how to track down meaningful error messages here.

2024-11-18 07:17 UTC, robertomonteromiguel commented
> @natitsechanski @robertomonteromiguel I'm having a really tough time debugging the Java errors here. Beyond that, since there are some expected-failing tests, it's not clear to me how to track down meaningful error messages here.

Checking the logs, there are failures on the java installation process. Like this:

` ` ` dpkg: error processing package ca-certificates-java (--configure):
     installed ca-certificates-java package post-installation script subprocess returned error exit status 1
    Setting up default-jre-headless (2:1.11-71) ...
    dpkg: dependency problems prevent configuration of openjdk-11-jre-headless:arm64:
     openjdk-11-jre-headless:arm64 depends on ca-certificates-java (>= 20190405~); however:
      Package ca-certificates-java is not configured yet.
`` `

2024-11-18 15:28 UTC, emmettbutler commented
@robertomonteromiguel are there instructions anywhere about how to run the machine locally?

2024-12-04 13:51 UTC, robertomonteromiguel requested changes
There are several failures in the pipeline. Check here: https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/50273096

For example, debian 10 is installing python 2.7. You should exclude in the normal scenario and add to the unsupported scenario.
Nodejs is failing due to debian 10 can find the package nodejs

2025-07-01 15:56 UTC, closed without merging