Revert "Revert "[python] update telemetry configuration names""
DataDog/system-tests pull request #3250
Opened 2024-10-16 13:22 UTC by mabdinur

Reverts DataDog/system-tests#3245

2024-10-16 14:37 UTC, mabdinur commented on tests/parametric/test_telemetry.py
```suggestion

        if context.library == "java":
            outcome_value = str(outcome_value).lower()
```

2024-10-17 06:02 UTC, robertomonteromiguel requested changes
There are CI failures related with this PR

2024-10-17 13:22 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +    @missing_feature(context.library < "python@2.16.0", reason="Reports configurations with unexpected names")
```suggestion
    @missing_feature(context.library <= "python@2.16.0", reason="Reports configurations with unexpected names")
```

2024-10-17 13:22 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +    @missing_feature(context.library < "python@2.16.0", reason="Reports configurations with unexpected names")
```suggestion
    @missing_feature(context.library <= "python@2.16.0", reason="Reports configurations with unexpected names")
```

2024-10-17 13:22 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +    @missing_feature(context.library < "python@2.16.0", reason="Reports configurations with unexpected names")
```suggestion
    @missing_feature(context.library <= "python@2.16.0", reason="Reports configurations with unexpected names")
```

2024-10-17 13:22 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +        context.library < "python@2.16.0", reason="Converts boolean values to strings",
```suggestion
        context.library <= "python@2.16.0", reason="Converts boolean values to strings",
```

2024-10-17 13:22 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +        context.library < "python@2.16.0",
```suggestion
        context.library <= "python@2.16.0",
```

2024-10-17 14:31 UTC, robertomonteromiguel approved these changes

2024-10-17 16:18 UTC, merged