updating trace_context_precedence test to include flag test
DataDog/system-tests pull request #3276
Opened 2024-10-21 15:43 UTC by mhlidd

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-10-22 05:41 UTC, robertomonteromiguel requested changes
There are failures on the CI related with this PR

2024-11-07 14:38 UTC, cbeauchesne commented on tests/parametric/test_headers_precedence.py
> +    @irrelevant(context.library < "java@v1.43.0", reason="not implemented yet")
I think the good marker here is `missing_feature`, why do you think it should be `irrelevant` ? 🤔

2024-11-07 14:58 UTC, mabdinur approved these changes
Left some nits, overall LGTM!

2024-11-07 14:58 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +        Ensure the last parent id tag is set according to the W3C phase 3 spec
Can we update this doc string

2024-11-07 14:58 UTC, mabdinur commented on tests/parametric/test_headers_precedence.py
> +    @missing_feature(context.library < "java@v1.43.0", reason="not implemented yet")
Can we make the reason more descriptive

2024-11-07 21:25 UTC, zacharycmontoya commented on tests/parametric/test_headers_precedence.py
> +        Ensure the flags and tracestate fields are properly set in the span links
```suggestion
        Ensure the flags field is properly set in the span links
```

2024-11-07 21:25 UTC, zacharycmontoya commented on tests/parametric/test_headers_precedence.py
> +        Ensure the flags and tracestate fields are properly set in the span links
```suggestion
        Ensure the tracestate field is properly set in the span links
```

2024-11-11 15:14 UTC, merged