Updating how to run binaries for Golang
DataDog/system-tests pull request #3320
Opened 2024-10-25 12:40 UTC by mhlidd

## Motivation

Cleaning up clutter and clarifying how to run golang binaries in the System-Tests repo.

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-10-25 12:55 UTC, robertomonteromiguel approved these changes

2024-10-25 13:02 UTC, mtoffl01 requested changes

2024-10-25 13:02 UTC, mtoffl01 commented on docs/execute/binaries.md
> +To test unmerged PRs locally, run the following in the utils/build/docker/golang/parametric directory:
The examples below don't show how to run an unmerged commit (although hard to give an example without a real commit hash 😆 ), and that's exactly what I was confused about when I first ran these tests.
Maybe let's change line 31 to be more descriptive:
```suggestion
To test unmerged PRs locally, you'll first need to identify a git commit hash that contains your changes. If your changes have not yet been pushed to a remote branch, you can run `git log` locally and capture the latest (or most relevant) commit hash. If your changes are pushed to github, you can copy the latest (or most relevant) commit hash from the github UI on your open PR.
Once you have the commit hash, run the following in the utils/build/docker/golang/parametric directory:
```

2024-10-25 20:26 UTC, mhlidd commented
/merge

2024-10-25 20:31 UTC, mhlidd commented
/remove

2024-10-29 14:24 UTC, mtoffl01 requested changes

2024-10-29 15:12 UTC, mtoffl01 approved these changes

2024-10-29 15:14 UTC, merged