chore: more span pointer tests
DataDog/system-tests pull request #3330
Opened 2024-10-28 17:22 UTC by apiarian-datadog

## Motivation

Now that span pointers for s3 and dynamodb are going to be released and we're starting work on the javascript tracer, let's add more tests.

## Changes

Adding system tests for s3: copy object and complete multipart upload; and dynamod: put item, update item, delete item, batch write item, and transact write items.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-10-30 14:02 UTC, apiarian-datadog commented
test failures seem to be unrelated to the changes here.

2024-10-30 17:17 UTC, cbeauchesne requested changes

2024-10-30 17:17 UTC, cbeauchesne commented on tests/serverless/span_pointers/utils.py
> +        print(span)
```suggestion
        logger.info(span)
```

2024-10-30 17:53 UTC, apiarian-datadog commented on tests/serverless/span_pointers/utils.py
> +        print(span)
it's gone!

2024-10-30 17:56 UTC, nhulston approved these changes
LGTM!

2024-10-31 11:28 UTC, cbeauchesne approved these changes

2024-11-04 20:52 UTC, apiarian-datadog commented
remaining test failures are not relevant.

2024-11-04 20:52 UTC, merged