add ssi test matrix for nodejs
DataDog/system-tests pull request #3333
Opened 2024-10-29 00:54 UTC by rochdev

## Motivation

We are only testing Node 18 otherwise.

## Changes

Add SSI test matrix for Node.js

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-11-04 07:57 UTC, robertomonteromiguel requested changes
Why are we creating a new weblog called "test-app-nodejs-latest"? I advocate putting everything inside test-app-nodejs-multicontainer.
We are not using the suffix “latest” in any other language or variant. I think we should try to maintain naming homegeneity among all languages.

2024-11-04 23:37 UTC, rochdev commented
> Why are we creating a new weblog called "test-app-nodejs-latest"? I advocate putting everything inside test-app-nodejs-multicontainer.

This is answered in the description of the PR.

2024-11-05 13:44 UTC, robertomonteromiguel commented
> > Why are we creating a new weblog called "test-app-nodejs-latest"? I advocate putting everything inside test-app-nodejs-multicontainer.
> 
> This is answered in the description of the PR.

Upps, right.
Ok. Ideally we should put the missing_feature or bug marker. I am now working on a PR that will allow us to do that.

2024-11-08 10:01 UTC, robertomonteromiguel commented
@rochdev I merged the PR that allow you to mark the test as bug for a runtime_version.
You should add the "latest" containers inside of "mutlicontainer" and mark the tests, like this:
``` @features.installer_auto_instrumentation
@scenarios.simple_installer_auto_injection
class TestSimpleInstallerAutoInjectManual(base.AutoInjectBaseTest):
    @flaky(weblog_variant="test-app-java-buildpack", reason="APMON-1595")
    @parametrize_virtual_machines(
        bugs=[
            {"library": "nodejs", "runtime_version":"19", "reason": "INPLAT-103"},
        ]
    )
    def test_install(self, virtual_machine):```

I didn't implement the "missing_feature", let's use the bug marker

2024-11-11 18:02 UTC, rochdev commented
@robertomonteromiguel Updated the PR according to our latest discussion. Thanks for the tips, it definitely simplifies this PR to not need a separate provisioner just for latest 😄

2024-11-11 21:23 UTC, rochdev commented on utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-multicontainer.yml
> -    nginx_config: utils/build/virtual_machine/weblogs/nodejs/test-app-nodejs-multicontainer/nginx.conf
Ah sorry I assumed it was because of the split between `multicontainer` and `latest`.

2024-11-11 21:24 UTC, rochdev commented on utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-multicontainer.yml
> -    nginx_config: utils/build/virtual_machine/weblogs/nodejs/test-app-nodejs-multicontainer/nginx.conf
Done!

2024-11-12 06:59 UTC, robertomonteromiguel approved these changes

2024-11-12 14:52 UTC, merged