Paullgdc/custom agent version
DataDog/system-tests pull request #334
Opened 2022-05-02 10:03 UTC by paullegranddc

2022-05-04 08:26 UTC, cbeauchesne requested changes
Could you have a look on their CircleCi build job ?

2022-05-04 08:26 UTC, cbeauchesne commented on utils/build/docker/agent.Dockerfile
> +ARG AGENT_IMAGE=datadog/agent:7
latest ?

2022-05-04 08:26 UTC, cbeauchesne commented on utils/build/build.sh
> +            read -r AGENT_BASE_IMAGE < ./binaries/agent-image
AGENT_BASE_IMAGE=$(cat ...)

2022-05-04 08:26 UTC, cbeauchesne commented on utils/build/build.sh
> +echo "AGENT_BASE_IMAGE:" $AGENT_BASE_IMAGE
Remove this (not needed)

2022-06-02 14:55 UTC, merged

2022-06-02 15:33 UTC, paullegranddc commented
🔥