ruby test matrix [INPLAT-41]
DataDog/system-tests pull request #3347
Opened 2024-10-30 16:10 UTC by emmettbutler

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-10-30 19:42 UTC, emmettbutler commented
This test currently fails when attempting to find the trace. We should probably skip it and then merge.

2024-10-31 08:20 UTC, robertomonteromiguel requested changes
I see this error when we build the container:

`
    #47 [ruby_3_1  3/10] RUN locale-gen en_US.UTF-8
    #47 1.432 /bin/sh: locale-gen: not found
    #47 CANCELED
    failed to solve: process "/bin/sh -c locale-gen en_US.UTF-8" did not complete successfully: exit code: 127
    ------
     > [ruby_2_7  3/10] RUN locale-gen en_US.UTF-8:
    locale-gen: not found`

2024-11-05 07:26 UTC, robertomonteromiguel requested changes
The PR looks good.
Only small change before merge it

2024-11-05 07:26 UTC, robertomonteromiguel commented on utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby-multialpine.yml
> +    exact_os_branches: [ubuntu24]
We'll set this by command line. We should remove this from here, because actually it should work on all vms

2024-11-05 07:26 UTC, robertomonteromiguel commented on utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby-multicontainer.yml
> +    exact_os_branches: [ubuntu24]
remove

2024-11-06 16:01 UTC, robertomonteromiguel approved these changes

2024-11-06 17:32 UTC, merged