dotnet test matrix [INPLAT-44]
DataDog/system-tests pull request #3348
Opened 2024-10-30 17:05 UTC by emmettbutler

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-10-31 08:26 UTC, robertomonteromiguel requested changes
It's failing when the app container is built:

`dotnet_8-1      | [datadog_preload_hook] done waiting!
dotnet_8-1      | [datadog_preload_hook] re-exec required
dotnet_8-1      | [datadog_preload_hook] argv[0]: 'dotnet'
dotnet_8-1      | 
dotnet_8-1      | [datadog_preload_hook] argv[1]: 'MinimalWebApp.dll'
dotnet_8-1      | 
dotnet_8-1      | [datadog_preload_hook] debug flag set, running injection
dotnet_8-1      | [datadog_preload_hook] re-execution of library, not re-injecting
dotnet_8-1      | You must install or update .NET to run this application.
dotnet_8-1      | 
dotnet_8-1      | App: /app/MinimalWebApp.dll
dotnet_8-1      | Architecture: x64
dotnet_8-1      | Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
dotnet_8-1      | .NET location: /usr/share/dotnet/
dotnet_8-1      | 
dotnet_8-1      | The following frameworks were found:
dotnet_8-1      |   8.0.10 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
dotnet_8-1      | 
dotnet_8-1      | Learn more:
dotnet_8-1      | https://aka.ms/dotnet/app-launch-failed
dotnet_8-1      | 
dotnet_8-1      | To install missing framework, download:`

2024-11-01 18:31 UTC, emmettbutler commented
The new tests are passing on this change. @robertomonteromiguel @andrewlock I think it's reviewable now.

cc @brettlangdon

2024-11-04 08:07 UTC, robertomonteromiguel requested changes

2024-11-04 08:07 UTC, robertomonteromiguel commented on .gitlab-ci.yml
> +          ONBOARDING_FILTER_WEBLOG: [test-app-dotnet,test-app-dotnet-container,test-app-dotnet-multicontainer,test-app-dotnet-multialpine]
If we use the variant "test-app-dotnet-multicontainer", we don't need to execute the variant "test-app-dotnet-container"
Could we remove the "test-app-dotnet-container" from the pipeline? only remove from the pipeline, don't remove the variant folders and files

2024-11-05 07:04 UTC, robertomonteromiguel approved these changes

2024-11-06 15:59 UTC, merged