parametric: ensure config consistency tests are compatible with ruby [WIP]
DataDog/system-tests pull request #3381
Opened 2024-11-05 18:45 UTC by mabdinur

## Motivation

Resolves the following errors: https://github.com/DataDog/system-tests/actions/runs/11689546728/job/32553275066 in the v2.5.0 release of the ruby tracer.

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-11-13 21:51 UTC, mabdinur commented on tests/parametric/test_config_consistency.py
>      def test_specific_version(self, library_env, test_agent, test_library):
```suggestion
    @missing_feature(library < "ruby@2.7.0.dev")
    def test_specific_version(self, library_env, test_agent, test_library):
```

2024-11-13 21:51 UTC, mabdinur commented on tests/parametric/test_config_consistency.py
> +            with test_library.start_span(name="s1", service="version_test") as s1:
```suggestion
            with test_library.start_span(name="s1") as s1:
```

2024-11-18 16:15 UTC, mabdinur commented on tests/parametric/test_config_consistency.py
> +    @bug(context.library == "golang", reason="APMAPI-390")
```suggestion
    @ missing_feature(library == "golang", reason="APMAPI-390")
```

2024-11-18 17:50 UTC, mabdinur commented on tests/parametric/test_config_consistency.py
> +    @missing_feature(library < "ruby@2.7.0.dev")
```suggestion
    @missing_feature(context.library < "ruby@2.7.0.dev")
```

2024-11-19 08:54 UTC, cbeauchesne requested changes
Failing in CI : https://github.com/DataDog/system-tests/actions/runs/11898131960/job/33154324222?pr=3381#step:5:270

2024-11-19 15:17 UTC, mabdinur commented
> Failing in CI : https://github.com/DataDog/system-tests/actions/runs/11898131960/job/33154324222?pr=3381#step:5:270

[Fix](https://github.com/DataDog/dd-trace-rb/pull/4075) will be released in v2.8.0. I will update the version

2024-11-19 15:18 UTC, mabdinur commented on tests/parametric/test_config_consistency.py
> +    @missing_feature(context.library < "ruby@2.7.0.dev")
```suggestion
    @missing_feature(context.library < "ruby@2.8.0.dev")
```

2024-11-19 15:49 UTC, cbeauchesne commented
You can declare it valid for `2.7.1-dev`, it will skip the test for `2.7.0`, and enable it for your main branch

2024-11-20 08:56 UTC, cbeauchesne commented
Updating the branch to fix failure.

2024-11-20 11:56 UTC, cbeauchesne approved these changes

2024-11-20 19:48 UTC, merged