Go: fix agentURL startup log
DataDog/system-tests pull request #3393
Opened 2024-11-06 18:51 UTC by rachelyangdog

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-11-06 19:36 UTC, mabdinur commented on tests/parametric/test_config_consistency.py
> +
```suggestion
```

2024-11-06 19:37 UTC, mabdinur approved these changes
Can we update the PR description. Aside from that LGTM

2024-11-06 20:22 UTC, mtoffl01 requested changes
Make sure to update the Golang manifest file (manifests/golang.yml) to specify the version of dd-trace-go where this fix will be included.
(Probably 1.70.0-dev).

2024-11-06 20:22 UTC, mtoffl01 commented on tests/parametric/test_config_consistency.py
> -    @bug(context.library == "golang", reason="APMAPI-390")
Be sure to update APMAPI-390 accordingly.

2024-11-08 19:39 UTC, ZStriker19 approved these changes

2024-11-08 20:28 UTC, mtoffl01 approved these changes

2024-11-08 21:00 UTC, merged