adding mypy to parametric tests
DataDog/system-tests pull request #3405
Opened 2024-11-07 20:54 UTC by rachelyangdog

## Motivation
Update the ./format.sh script to run static analysis checks on parametric tests (via mypy). 

## Changes
Updated mypy and fixed all errors. (as of now a lot of fixes are # type: ignore)

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-11-07 21:08 UTC, mabdinur commented on tests/parametric/test_tracer.py
> +        assert span["name"] == "operation"  # type: ignore
Instead of ignoring the failing checks can we fix the typing issues

2024-11-08 16:45 UTC, cbeauchesne requested changes
Could do the fix only for utils/parametric and tests/parametric

2024-11-08 16:45 UTC, cbeauchesne commented on format.sh
> +if ! mypy tests/parametric utils/parametric; then
Just call mypy here, and configure it to look only in parametric in configuration file

2024-11-08 16:45 UTC, cbeauchesne commented on mypy.ini
> +[mypy]
Could you use `pyproject.toml` ?

2024-11-08 16:45 UTC, cbeauchesne commented on utils/build/docker/golang/go.work.sum
>  github.com/BurntSushi/xgb v0.0.0-20160522181843-27f122750802 h1:1BDTz0u9nC3//pOCMdNH+CiXJVYJh5UQNCOBG7jbELc=
Is it intentend to be hre ?

2024-11-08 16:45 UTC, cbeauchesne commented on format.sh
> +  black --quiet --check --diff .
This line is executed in the CI, and it's easier to have the file list to fix printed out at the end of the process.

```suggestion
  black --check --diff .
```

2024-11-14 09:00 UTC, cbeauchesne requested changes

2024-11-15 16:06 UTC, rachelyangdog commented on utils/parametric/spec/trace.py
> +    OkSummary: Optional[BaseDDSketch]
Yes, because `OkSummary` is set to None sometimes when it is used and mypy doesn't like that the type is set to BaseDDSketch

2024-11-15 19:06 UTC, rachelyangdog commented on utils/parametric/spec/trace.py
> +    OkSummary: Optional[BaseDDSketch]
I think BaseDDSketch is set to None at some point and mypy doesn't like that

2024-11-15 19:07 UTC, rachelyangdog commented on utils/_context/_scenarios/parametric.py
> +            return None
By default, mypy will generate errors when a function is missing return statements

2024-11-18 09:05 UTC, cbeauchesne commented
> [continue reverting to main](https://github.com/DataDog/system-tests/pull/3405/commits/352807280f7a2d9fdaf79a76161bb4f25d40a7e5)

Do you need any help ?

2024-11-18 20:21 UTC, closed without merging

2024-11-18 20:21 UTC, rachelyangdog commented
moved this PR to new smaller PR excluding non parametric files