[python] add test-app-python-27 app for INSTALLER_NOT_SUPPORTED_AUTO_INJECTION
DataDog/system-tests pull request #3455
Opened 2024-11-13 16:12 UTC by emmettbutler

## Motivation

We are currently not running the `INSTALLER_NOT_SUPPORTED_AUTO_INJECTION` scenario for Python 2.7. This change adds a test case for that.

## Changes

Adds a new `test-app-python-27` VM weblog

Starts running the `INSTALLER_NOT_SUPPORTED_AUTO_INJECTION` scenario with this new app

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-11-13 21:12 UTC, emmettbutler commented
@brettlangdon @robertomonteromiguel I think the failing tests on this PR are the result of dd-trace-py not working under py27. That's to say, the test has uncovered a real bug. Shall I mark as skipped for the moment and merge?

2024-11-14 00:29 UTC, brettlangdon commented on lib-injection/build/docker/python/dd-lib-python-init-test-django-27/Dockerfile
> +FROM python:3.11
```suggestion
FROM python:2.7
```

?

2024-11-14 00:32 UTC, brettlangdon reviewed
```
[datadog_preload_hook] done waiting!
'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "/home/datadog/.pyenv/versions/2.7.18/lib/python2.7/site-packages/django/__main__.py", line 9, in <module>
    management.execute_from_command_line()
  File "/home/datadog/.pyenv/versions/2.7.18/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/datadog/.pyenv/versions/2.7.18/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/datadog/.pyenv/versions/2.7.18/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/datadog/.pyenv/versions/2.7.18/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/datadog/.pyenv/versions/2.7.18/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/datadog/.pyenv/versions/2.7.18/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_app
```

> 'import sitecustomize' failed; use -v for traceback

This makes a lot of sense

> ImportError: No module named django_app

Maybe `PYTHONPATH` is treated differently for Python 2.7 and it needs an explicit `export PYTHONPATH=/home/datadog/:$PYTHONPATH`... maybe?

2024-11-14 13:49 UTC, emmettbutler commented
@brettlangdon attempted that in https://github.com/DataDog/system-tests/pull/3455/commits/34ac1556d187a6d9641ec0f4522b505c0fcd0c58

2024-11-18 07:20 UTC, robertomonteromiguel requested changes

2024-11-18 07:20 UTC, robertomonteromiguel commented on utils/_context/virtual_machines.py
> +            os_branch="redhat_9",
Restore this. Currently we have disabled the RH9

2024-11-18 18:56 UTC, brettlangdon approved these changes
minor comments/suggestions only.

2024-11-19 17:55 UTC, emmettbutler commented on utils/build/virtual_machine/weblogs/python/provision_test-app-python-27.yml
> +            local_path: lib-injection/build/docker/python/dd-lib-python-init-test-django-27
I tried that, but there's a small diff between the versions of django_app.py.

2024-11-19 18:08 UTC, brettlangdon approved these changes
one missed 3.6 file, and I _think_ the `redhat_9`s need to be `redhat` (if I understand Roberto's previous comments correctly), otherwise lgtm

2024-11-19 18:08 UTC, brettlangdon commented on utils/build/virtual_machine/weblogs/python/provision_test-app-python-36.yml
We can remove this file, right?

2024-11-19 18:08 UTC, brettlangdon commented on utils/_context/virtual_machines.py
> +            os_branch="redhat_9",
```suggestion
            os_branch="redhat",
```

2024-11-19 18:08 UTC, brettlangdon commented on utils/build/virtual_machine/weblogs/python/provision_test-app-python-27.yml
> +    excluded_os_branches: [amazon_linux2, rhel_7_amd64, redhat_9]
```suggestion
    excluded_os_branches: [amazon_linux2, rhel_7_amd64, redhat]
```

2024-11-19 18:08 UTC, brettlangdon commented on utils/build/virtual_machine/weblogs/python/provision_test-app-python-27.yml
> +    excluded_os_branches: [amazon_linux2, rhel_7_amd64, redhat_9]
```suggestion
    excluded_os_branches: [amazon_linux2, rhel_7_amd64, redhat]
```

2024-11-19 20:05 UTC, brettlangdon approved these changes

2024-11-20 14:16 UTC, robertomonteromiguel approved these changes
I only added the exclusion for ubuntu23 for this weblog and now it's working. We could merge this PR. Thanks Emmet for your work!

2024-11-20 14:52 UTC, merged