parametric: enable python otel env telemetry tests
DataDog/system-tests pull request #3497
Opened 2024-11-19 18:42 UTC by mabdinur

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-11-20 17:51 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +            otelsampler_config = "otel_traces_sampler_args"
```suggestion
            otelsampler_config = "otel_traces_sampler_arg"
```

2024-11-20 17:51 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +            otelsampler_config = "otel_traces_sampler_args"
```suggestion
            otelsampler_config = "otel_traces_sampler_arg"
```

2024-11-20 18:56 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +            ["dd_tags", "otel_resource_attributes"],
```suggestion
            # ["dd_tags", "otel_resource_attributes"], not supported by nodejs
```

2024-11-21 07:14 UTC, robertomonteromiguel approved these changes

2024-11-22 15:56 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +            # ["dd_tags", "otel_resource_attributes"], not supported by nodejs
```suggestion
            # ["dd_tags", "otel_resource_attributes"],
```

2024-11-22 15:57 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +    @missing_feature(context.library < "python@2.18.0.dev", reason="Not implemented")
```suggestion
    @missing_feature(context.library == "does not collect invalid metrics for otel_resource_attributes", reason="nodejs")
```

2024-11-22 16:21 UTC, robertomonteromiguel requested changes
lint failures

2024-11-22 18:21 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +        context.library == "does not collect env.invalid metrics for otel_resource_attributes", reason="nodejs"
```suggestion
        context.library == "nodejs", reason="does not collect env.invalid metrics for otel_resource_attributes"
```

2024-11-22 18:22 UTC, mabdinur commented on tests/parametric/test_telemetry.py
> +        context.library == "nodejs", reason="does not collect env.invalid metrics for otel_resource_attributes"
```suggestion
        context.library == "nodejs", reason="does not collect otel_env.invalid metrics for otel_resource_attributes"
```

2024-11-22 19:57 UTC, mabdinur commented on tests/parametric/test_telemetry.py
>      @missing_feature(context.library == "cpp", reason="Not implemented")
```suggestion
    @missing_feature(context.library == "cpp", reason="Not implemented")
    @missing_feature(context.library < "python@2.18.0.dev", reason="Not implemented")
```

2024-11-25 10:04 UTC, cbeauchesne approved these changes

2024-11-26 07:41 UTC, robertomonteromiguel approved these changes

2024-11-26 17:46 UTC, merged