Tests for standard tags required by ASM
DataDog/system-tests pull request #358
Opened 2022-05-20 08:25 UTC by robertpi

2022-05-20 08:59 UTC, cbeauchesne requested changes

2022-05-20 08:59 UTC, cbeauchesne commented on scenarios/test_library_conf.py
> +    @released(dotnet="2.1.0", golang="?", java="?", nodejs="?", php_appsec="?", python="?", ruby="?")
`released` decorator is only valid on class. Basically: 

* one class <=> on feature
* N method => N use cases

2022-05-20 08:59 UTC, cbeauchesne commented on scenarios/test_library_conf.py
> +class Test_HeaderTags(BaseTestCase):
Could you add `coverage` decorator ? Reminder : 

* `@coverage.basic` => most simple test case, it ensures at least that the main use case of the feature is working
* `@coverage.complete` => You are confortable to says that a bug can't happen if the test is sucessful (at least for contexts covered by your weblogs)
* `@coverage.good` => everything else

2022-05-20 08:59 UTC, cbeauchesne commented on tests/test_standard_tags.py
> +class Test_StandardTags(BaseTestCase):
Same remark : move `released` here and add `coverage`

2022-05-20 08:59 UTC, cbeauchesne commented on scenarios/test_library_conf.py
> +class Test_HeaderTags(BaseTestCase):
Could you add `coverage` decorator ? Reminder : 

* `@coverage.basic` => most simple test case, it ensures at least that the main use case of the feature is working
* `@coverage.complete` => You are confortable to says that a bug can't happen if the test is sucessful (at least for contexts covered by your weblogs)
* `@coverage.good` => everything else

2022-05-20 08:59 UTC, cbeauchesne commented on utils/interfaces/_library/miscs.py
> +                        if tagKey not in self.tags:
maybe that instead ? 

```suggestion
                        if tagKey not in span["meta"]:
```

2022-05-20 08:59 UTC, cbeauchesne commented on utils/interfaces/_library/miscs.py
> +                    self.set_failure(f"{m(self.message)} not validated: {e}\nSpan is: {span}")
Giving the file name helps a lot : 

```suggestion
                    self.set_failure(f"{m(self.message)} not validated in {data['log_filename']}:\n{e}\nSpan is: {span}")
```

2022-05-20 09:00 UTC, cbeauchesne commented
For the linter, here is an how to : https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md

2022-05-20 10:35 UTC, cbeauchesne commented
I may know why it's failing. We put a watermark in this headers, to be able to correlate the request and the trace . But as there is no appsec event, the user-agent header is not reported in the trace. Give me some time, I'll have a look.

2022-05-20 10:40 UTC, cbeauchesne commented
I think you need to add `user-agent:http.request.headers.user-agent` in your custom `DD_TRACE_HEADER_TAGS`, it will solve issues

2022-05-20 11:36 UTC, cbeauchesne commented
Don't worry about failures on sinatra 14, 20 and 21, it's not related and being corrected soon by Loic.

2022-05-21 09:53 UTC, robertpi commented
@cbeauchesne Seems, everything's passing expect the sinatra tests. I'm out Monday, but could we get this merged anyway?

2022-05-23 08:26 UTC, cbeauchesne approved these changes

2022-05-23 08:26 UTC, merged