always define DDTRACE_2_7_0_OR_GREATER and DDTRACE_2_23_0_OR_GREATER
DataDog/system-tests pull request #3720
Opened 2024-12-18 18:08 UTC by lucaspimentel

## Motivation

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2024-12-19 07:26 UTC, robertomonteromiguel requested changes
After the change I can see the library version in the endtoend scenarios:
```Library: dotnet@3.8.0+0```
In the main branch execution I see:
```Library: dotnet@3.8.0```
After the change  I can see the library version in the paramettric scenario:
```Library: dotnet@3.8.0```
is this correct?

2024-12-19 14:53 UTC, lucaspimentel commented on utils/build/docker/dotnet/weblog/Endpoints/HealthcheckEndpoint.cs
> +                var version = Assembly.Load("Datadog.Trace").GetName().Version?.ToString(4);
That's it, thanks. I noticed this issue and I thought I had changed it from 4 to 3. Seems like I lost that commit somewhere 😬

2024-12-19 14:54 UTC, lucaspimentel commented on utils/build/docker/dotnet/weblog/Endpoints/HealthcheckEndpoint.cs
> +                var version = Assembly.Load("Datadog.Trace").GetName().Version?.ToString(4);
Oh, this in in `weblog`. Thanks!

2024-12-19 17:50 UTC, cbeauchesne approved these changes

2024-12-19 18:37 UTC, lucaspimentel commented on utils/build/docker/dotnet/weblog/Endpoints/HealthcheckEndpoint.cs
> +                var version = Assembly.Load("Datadog.Trace").GetName().Version?.ToString(4);
@robertomonteromiguel this fixes the issue in your comment.

2024-12-20 07:04 UTC, robertomonteromiguel approved these changes

2024-12-20 13:31 UTC, merged