re-enabled aws tests
DataDog/system-tests pull request #3733
Opened 2024-12-19 19:55 UTC by wconti27

## Motivation

re-enable AWS tests using localstack

## Changes

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2025-01-22 14:04 UTC, cbeauchesne requested changes
Could you resolve the conflict? 

I'm sorry for the delay, I may have missed this PR

2025-02-03 20:58 UTC, wconti27 commented
> Could you resolve the conflict?
> 
> I'm sorry for the delay, I may have missed this PR

Resolved! And no worries, but we should definitely get this in soon!

2025-02-04 08:24 UTC, cbeauchesne requested changes
Also, CI is failing

2025-02-04 08:24 UTC, cbeauchesne commented on utils/_context/containers.py
> +            image_name="softwaremill/elasticmq-native:latest",
Could you pin the version ? updates of `latest` may break system-tests

2025-02-04 08:24 UTC, cbeauchesne commented on utils/_context/_scenarios/integrations.py
> +        # if not self.replay:
Is it expected ?

2025-02-04 08:24 UTC, cbeauchesne commented on utils/_context/containers.py
> +            image_name="localstack/localstack:latest",
Same

2025-02-04 17:30 UTC, wconti27 commented on utils/_context/containers.py
> +            image_name="softwaremill/elasticmq-native:latest",
done.

2025-02-04 17:30 UTC, wconti27 commented on utils/_context/_scenarios/integrations.py
> +        # if not self.replay:
removed.

2025-02-04 17:30 UTC, wconti27 commented on utils/_context/containers.py
> +            image_name="localstack/localstack:latest",
done. pinned it.

2025-02-05 15:09 UTC, cbeauchesne commented on utils/_context/_scenarios/integrations.py
> -        if not self.replay:
Why removing this ?

2025-02-05 15:12 UTC, cbeauchesne approved these changes
Just a small questions. If the change was on purpose, AGTM

2025-02-05 16:15 UTC, wconti27 commented on utils/_context/_scenarios/integrations.py
> -        if not self.replay:
We don't need to check for AWS env variables since we are no longer communicating with actual AWS

2025-02-05 16:16 UTC, merged