[java] Add tests for database sources in springboot
DataDog/system-tests pull request #3742
Opened 2024-12-24 10:02 UTC by Mariovido

## Motivation

Add new test for java to check that **SQL Injection** with database sources is supported.

## Changes

- Added only system test for weblog variant **springboot**.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2025-01-08 10:44 UTC, jandro996 requested changes
Tests are failing for spring-boot variants 😅

2025-01-17 07:15 UTC, robertomonteromiguel requested changes
The TestSqlRow is also used in nodejs. Could impact your changes on nodejs? We are only testing this change for java

2025-01-17 09:27 UTC, smola requested changes

2025-01-17 09:27 UTC, smola commented on manifests/java.yml
> +            akka-http: missing_feature
If the issue is that the endpoint is not implemented, please, use `missing_feature (endpoint not implemented)`. Makes it easier for the next person to know what's going on.

2025-01-17 09:56 UTC, Mariovido commented on manifests/java.yml
> +            akka-http: missing_feature
Changed :)

2025-01-17 11:38 UTC, jandro996 approved these changes
LGTM! BTW is there any reason to not implement the endpoints on the other variants?

2025-01-17 13:19 UTC, robertomonteromiguel approved these changes

2025-01-21 09:39 UTC, smola approved these changes

2025-01-21 10:58 UTC, merged

2025-01-21 14:10 UTC, cbeauchesne commented
> [Mariovido](https://github.com/Mariovido) changed the title Add tests for database sources in springboot [java] Add tests for database sources in springboot [4 hours ago](https://github.com/DataDog/system-tests/pull/3742#event-16010636221)

@Mariovido when the test logic is modified, you should not use title prefix. I understand that it was easier to have a quicker CI for the merge commit, but it happen too often to have issues, we really prefer to not take any risk. Thanks you 🙏