Khanayan123/add consistent config system tests
DataDog/system-tests pull request #3745
Opened 2024-12-25 01:58 UTC by khanayan123

## Motivation

Adds new system tests to assert config consistency

## Changes
Adds system tests for DD_TRACE_SAMPLING_RULES, DD_LOG_INEJCTION, DD_RUNTIME_METRICS_ENABLED, & DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED as per https://docs.google.com/document/d/1kI-gTAKghfcwI7YzKhqRv2ExUstcHqADIWA4-TZ387o/edit?usp=sharing

2025-01-03 15:20 UTC, mabdinur commented on utils/build/docker/nodejs/express/app.js
> +app.get('/log/library', (req, res) => {
Can we add a test for this new endpoint here: https://github.com/DataDog/system-tests/blob/main/tests/parametric/test_parametric_endpoints.py#L4. This will allow us to report to the feature parity dashboard on which endpoints are not implemented in different languages.

Also to make this endpoint more useful can we add the following required arguments:
 - log level (warn/error/info/debug/...), we can use an enum here and ensure the casing is always consistent.
 - message (right now it's optional)

2025-01-03 15:22 UTC, mabdinur commented on manifests/cpp.yml
> +    Test_Config_LogInjection_128Bit_TradeId_Default: missing_feature
Instead of missing feature can we use https://github.com/DataDog/system-tests/blob/25c79a3502d69e30d8ccf0461d15501ccbd0addf/docs/edit/skip-tests.md?plain=1#L5. Some of these fail because the the parametric apps do not implement the new endpoint.

2025-01-03 15:51 UTC, cbeauchesne reviewed
could you update your branch? it'll fix the issue on ruby

2025-01-06 18:51 UTC, simon-id commented on tests/parametric/test_128_bit_traceids.py
>      def test_datadog_128_bit_generation_enabled_by_default(self, test_agent, test_library):
would be nice to have this be a version check instead of removing the whole line, just like java is doing right above.
(same thing in line 412)

2025-01-06 18:53 UTC, simon-id commented on manifests/java.yml
> +    Test_Config_IntegrationEnabled_True: irrelevant (not applicable to Go because of how they do auto instrumentation)
this is the java manifest

2025-01-06 18:55 UTC, simon-id commented on manifests/nodejs.yml
> +      nextjs: irrelevant
are you sure those are irrelevant ? and not missing_feature instead ?

2025-01-06 21:19 UTC, khanayan123 commented on manifests/nodejs.yml
> +      nextjs: irrelevant
Those apps just don't implement the route that tests the feature, but the feature exists

2025-01-06 22:24 UTC, mabdinur commented on tests/parametric/test_trace_sampling.py
> +        """Glob should work by default without specifying the format"""
The assertions/spans in this test look identical to test_field_case_insensitivity. S
hould we add the `library_env` in this test to  test_field_case_insensitivity parameterized test? This way we have one test with 5 scenarios.

2025-01-06 22:24 UTC, mabdinur commented on tests/test_config_consistency.py
> +        pattern = rf'"dd":\{{"trace_id":"[^"]+","span_id":"\d+","service":"[^"]+","version":"[^"]+","env":"[^"]+"\}},"msg":"{self.message}"'
Should we make this pattern more permissive? If there's whitespace between the entries then the pattern will fail to match. Also it requires log correlation fields to be wrapped in curly brackets and the message to printed after a comma. Also the values may not always be wrapped in quotes. 

This is an example of a log message generated by the python tracer: 

Python docs: https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/python/

```
import ddtrace
import logging

FORMAT = ('%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] '
          '[dd.service=%(dd.service)s dd.env=%(dd.env)s dd.version=%(dd.version)s dd.trace_id=%(dd.trace_id)s dd.span_id=%(dd.span_id)s] '
          '- %(message)s')
logging.basicConfig(format=FORMAT)

log = logging.getLogger(__name__)

with ddtrace.tracer.trace("test"):
    log.error("test")
```

Output:
`2025-01-06 17:21:00,421 ERROR [__main__] [reproduction.py:20] [dd.service=Downloads dd.env= dd.version= dd.trace_id=677c574c000000001679fe710d0f33ba dd.span_id=10973182204132464872] - test`

2025-01-07 14:15 UTC, simon-id commented on manifests/nodejs.yml
> +      nextjs: irrelevant
irrelevant is for when something really makes no sense to test

2025-01-09 17:53 UTC, khanayan123 commented on tests/parametric/test_trace_sampling.py
> +        """Glob should work by default without specifying the format"""
I could just remove it from all the tests since I believe no language currently requires the glob environment variable

2025-01-09 20:21 UTC, khanayan123 commented on tests/test_config_consistency.py
> +        pattern = rf'"dd":\{{"trace_id":"[^"]+","span_id":"\d+","service":"[^"]+","version":"[^"]+","env":"[^"]+"\}},"msg":"{self.message}"'
I think the other way to solve this issue is to have weblog apps send json formatted logs

2025-01-09 20:21 UTC, khanayan123 commented on tests/test_config_consistency.py
> +        pattern = rf'"dd":\{{"trace_id":"[^"]+","span_id":"\d+","service":"[^"]+","version":"[^"]+","env":"[^"]+"\}},"msg":"{self.message}"'
That would make parsing easier

2025-01-10 20:28 UTC, zacharycmontoya commented on tests/test_config_consistency.py
> +        data = list(interfaces.library.get_data("/dogstatsd/v2/proxy"))[0]
There might be a race condition here. At least in .NET we submit runtime metrics every 10s, so we'll need to add some sort of wait or configure the delay in a similar fashion for both the Enabled case and the Default case

2025-01-13 18:40 UTC, mabdinur approved these changes

2025-01-13 18:40 UTC, mabdinur commented on manifests/ruby.yml
> +    Test_Config_RuntimeMetrics_Default: incomplete_test_app
Can we add a reason to these incomplete_test_app decorators

2025-01-13 18:40 UTC, mabdinur commented on tests/test_config_consistency.py
> +        print(55, dd)
Do we need this print?

2025-01-13 18:40 UTC, mabdinur commented on tests/test_config_consistency.py
> +        stdout.assert_absence(pattern)
We should avoid negative tests. This test could pass due to an unexpected format or the feature is not implemented. 

cc: @cbeauchesne, @bm1549: This is an example of a negative test. Here we want to verify that log injection is disabled when the DD_LOG_INJECTION_ENABLED environment variable is not set. If a library does not support log injection at all then this test would still pass and show up as an easy win. 

Should this test exist? I think it still provides value even if it could be misinterpreted in the FPD.

2025-01-13 21:10 UTC, mtoffl01 commented on tests/test_config_consistency.py
> +@scenarios.tracing_config_nondefault
`@scenarios.default`?

2025-01-14 02:09 UTC, khanayan123 commented on tests/parametric/test_128_bit_traceids.py
> +        [{"DD_TRACE_PROPAGATION_STYLE": "tracecontext", "DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED": "true"}],
The test in the file test_datadog_128_bit_generation_enabled_by_default already verifies that 128-bit generation is enabled by default. Other tests explicitly configure this setting to ensure that other aspects of the feature can be tested, even in scenarios where the language may not enable this functionality by default

2025-01-14 15:17 UTC, mtoffl01 approved these changes

2025-01-15 10:48 UTC, cbeauchesne commented on tests/test_config_consistency.py
> +        stdout.assert_absence(pattern)
is there anything (telemetry, logs) that shows that the tracers has disabled log injection ?

2025-01-15 15:43 UTC, mtoffl01 commented on tests/parametric/test_128_bit_traceids.py
> +        [{"DD_TRACE_PROPAGATION_STYLE": "tracecontext", "DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED": "true"}],
Hmm.. okay. Like we don't care whether DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED is true by default in this test, we just want to check what the behavior is when it is enabled?

I don't think we do that for other tests, but this isn't a blocker, it's fine. Maybe add a comment or something

2025-01-15 15:49 UTC, mtoffl01 commented on tests/test_config_consistency.py
> +    """Verify 128 bit traceid are disabled in log injection when DD_TRACE_128BIT_TRACE_ID=false"""
```suggestion
    """Verify 128 bit traceid are disabled in log injection when DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED=false"""
```

2025-01-15 15:53 UTC, mtoffl01 commented on tests/test_config_consistency.py
> +        assert re.match(r"\d+", trace_id), f"Invalid 64-bit trace_id: {trace_id}"
```suggestion
        assert re.match(r"^\d{1,20}$", trace_id), f"Invalid 64-bit trace_id: {trace_id}"
```
?

2025-01-16 10:41 UTC, cbeauchesne requested changes

2025-01-16 10:41 UTC, cbeauchesne commented on utils/_context/_scenarios/__init__.py
> +    runtime_metrics_enabled = EndToEndScenario(
Can you add this scenario in `.github/workflows/run-end-to-end.yml` ?

2025-01-17 14:32 UTC, cbeauchesne commented
seems good, just waiting for the CI to finish to approve the PR

2025-01-17 16:48 UTC, cbeauchesne approved these changes

2025-01-17 19:13 UTC, merged