[Nodejs] Add tests for untrusted deserialization
DataDog/system-tests pull request #3759
Opened 2024-12-31 15:48 UTC by IlyasShabi

## Motivation

Add system test for Untrusted deserialization vulnerability

## Changes

Added test for Untrusted deserialization vulnerability in express4, 5 and typescript

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

2025-01-06 16:25 UTC, cbeauchesne requested changes

2025-01-06 16:25 UTC, cbeauchesne commented on utils/scripts/load-binary.sh
> +    echo "DataDog/dd-trace-js#untrusted-deserialization" > nodejs-load-from-npm
leftover ?

2025-01-07 08:27 UTC, IlyasShabi commented on utils/scripts/load-binary.sh
> +    echo "DataDog/dd-trace-js#untrusted-deserialization" > nodejs-load-from-npm
Nop, will change it to master later

2025-01-09 09:18 UTC, uurien commented on manifests/nodejs.yml
> +  - &ref_5_31_0 '>=5.31.0 || ^4.55.0'
5.31.0 already released, It should be at least 5.32.0

2025-01-09 10:52 UTC, IlyasShabi commented on manifests/nodejs.yml
> +  - &ref_5_31_0 '>=5.31.0 || ^4.55.0'
Done

2025-01-17 13:58 UTC, uurien approved these changes

2025-01-17 14:02 UTC, cbeauchesne approved these changes

2025-01-17 14:03 UTC, merged