[IAST - Insecure hashing] New endpoints spring-boot(java) and express…
DataDog/system-tests pull request #412
Opened 2022-07-12 13:53 UTC by robertomonteromiguel

Add new endpoints to check insecure hash IAST
Add new test to check that endpoints are available (Does not check for vulnerability detection as long as it is not implemented in the library.)

2022-07-12 15:02 UTC, vdeturckheim commented on utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/CryptoExamples.java
> +}
```suggestion
}

```

2022-07-12 15:03 UTC, vdeturckheim commented on utils/build/docker/nodejs/express4/app.js
> +  console.log(outputHashes);
```suggestion
```
Do we need a log here?

2022-07-12 15:32 UTC, uurien commented on utils/build/docker/nodejs/express4/app.js
> +  var crypto = require('crypto');
You can use `const` instead of `var` for all `var` in those lines.

2022-07-13 12:33 UTC, cbeauchesne requested changes
Could you update `docs/weblog/README.md`, and details what this endpoint is supposed to do ?

2022-07-13 12:54 UTC, smola approved these changes
Sounds good. I just added a suggestion to test algorithms in independent requests. This would be particularly useful if/when we limit the number of reported vulnerabilities per request. Also to verify that every algorithm is checked (once we test for the vulnerability detection).

2022-07-13 12:54 UTC, smola commented on utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
> +		return CryptoExamples.InsecureHashingAlgorithm.stream()
I wonder if we want to pass the algorithm name (e.g. `md5`) in the request to test them independently?

2022-07-20 07:24 UTC, cbeauchesne approved these changes

2022-07-20 14:53 UTC, cbeauchesne approved these changes

2022-07-20 14:54 UTC, cbeauchesne commented
@robertomonteromiguel you can merge it when you want

2022-07-20 14:56 UTC, merged