feat(python/asm): GA 1.1 missing features
DataDog/system-tests pull request #492
Opened 2022-09-16 09:57 UTC by avara1986

2022-09-16 10:41 UTC, gnufede approved these changes

2022-09-16 15:36 UTC, cbeauchesne requested changes

2022-09-16 15:36 UTC, cbeauchesne commented on scenarios/appsec/test_conf.py
> +    @missing_feature(context.library < "python@{}".format(PYTHON_RELEASE_GA_1_1))
You can use f-strings : 

```suggestion
    @missing_feature(context.library < f"python@{PYTHON_RELEASE_GA_1_1}")
```

2022-09-19 09:28 UTC, cbeauchesne approved these changes

2022-09-19 10:01 UTC, merged