feat(python): IAST weak hash
DataDog/system-tests pull request #552
Opened 2022-10-07 13:41 UTC by avara1986

## Description

Please include a short summary of the change

## Check list

Your PR is not ready to be reviewed? Please save it as a draft :pray:

- [ ] Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
- [ ] CI is passing
- [ ] There is at least one approval from code owners

Yes to all? Feel free to merge it whenever you want :heart:

2022-10-10 06:14 UTC, robertomonteromiguel commented
python django and uwsgi build failed:

`  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/ddtrace/internal/module.py", line 190, in _exec_module
    self.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/urls.py", line 6, in <module>
    from iast import weak_hash, secure_algorithm
ModuleNotFoundError: No module named 'iast'
weblog exited with code 137
`

2022-10-25 15:05 UTC, juanjux approved these changes

2022-10-25 16:10 UTC, gnufede approved these changes

2022-10-27 09:58 UTC, cbeauchesne commented
Hi @avara1986, is this PR not a draft anymore, can I review it ?

2022-11-03 07:42 UTC, avara1986 commented
> Hi @avara1986, is this PR not a draft anymore, can I review it ?

Yes @cbeauchesne , I updated to "ready to review" :smile:

2022-11-03 18:05 UTC, cbeauchesne requested changes

2022-11-03 18:05 UTC, cbeauchesne commented on tests/appsec/iast/test_iast.py
> +    python="1.6.0rc1.dev",
This version does not exists yet. It means that the test is not executed. And once it'll exists, if the tracers does not pass the test, your CI will be broken (among a lot of other CI).

FYI, current dev version from your `main` branch is python@1.5.0rc2.dev105+g61f01775 : https://github.com/DataDog/system-tests/actions/runs/3386289779/jobs/5625523608#step:9:31

2022-11-11 08:52 UTC, juanjux approved these changes

2022-11-15 16:58 UTC, cbeauchesne commented
For a reason I ignore, GH did not run action on the last commit. I manually ran them : https://github.com/DataDog/system-tests/actions/runs/3472503367

2022-11-23 09:34 UTC, cbeauchesne approved these changes

2022-11-23 11:07 UTC, merged