chore ASM: enabling http.route for python
DataDog/system-tests pull request #555
Opened 2022-10-10 09:21 UTC by christophe-papazian

## Description

Enable http.route tests for Python.

## Check list

Your PR is not ready to be reviewed? Please save it as a draft :pray:

- [ ] Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
- [ ] CI is passing
- [ ] There is at least one approval from code owners

Yes to all? Feel free to merge it whenever you want :heart:

2022-10-14 08:18 UTC, cbeauchesne requested changes

2022-10-14 08:18 UTC, cbeauchesne commented on tests/test_standard_tags.py
> +@released(dotnet="2.13.0", golang="1.39.0", nodejs="2.11.0", php="?", python="1.6.0rc1.dev", ruby="?")
The current version of the tracer in githug is `python@1.5.0rc2.dev49+g57a03ec5` -> https://github.com/DataDog/system-tests/actions/runs/3242665553/jobs/5316283397#step:9:43

It means that the test is not executed here.

2022-11-07 14:00 UTC, cbeauchesne commented on tests/test_standard_tags.py
> +@released(dotnet="2.13.0", golang="1.39.0", nodejs="2.11.0", php="?", python="1.6.0rc1.dev", ruby="?")
@christophe-papazian did you saw my comment ?

2022-11-08 08:56 UTC, cbeauchesne requested changes

2022-11-08 08:56 UTC, cbeauchesne commented on tests/test_standard_tags.py
> +@released(dotnet="2.13.0", golang="1.39.0", nodejs="2.11.0", php="?", python="1.5.0rc2.dev", ruby="?")
As we don't know when it has been really released, can you put 1.6.0 here ?

2022-11-08 08:56 UTC, cbeauchesne commented on tests/test_standard_tags.py
> +            if context.weblog_variant == "flask":
```suggestion
            if context.weblog_variant == "flask-poc":
```

2022-11-08 09:50 UTC, cbeauchesne requested changes

2022-11-08 09:50 UTC, cbeauchesne commented on tests/test_standard_tags.py
> +                tags["http.route"] = "/sample_rate_route/<i>"
Well, this [failure](https://github.com/DataDog/system-tests/actions/runs/3418100849/jobs/5690011335#step:9:132) says that you need to add this : 

```python
            if context.weblog_variant in ("flask-poc", "uwsgi-poc"):
                tags["http.route"] = "/sample_rate_route/<i>"
            elif context.weblog_variant == "django-poc":
                tags["http.route"] = "sample_rate_route/<int:i>"
```

2022-11-11 11:25 UTC, avara1986 approved these changes

2022-11-15 10:36 UTC, cbeauchesne commented
@christophe-papazian ok to merge ?

2022-11-15 15:31 UTC, christophe-papazian commented
ok to merge !

2022-11-16 09:29 UTC, merged