feat(telemetry): add basic WAF telemetry metrics tests
DataDog/system-tests pull request #823
Opened 2023-01-31 15:36 UTC by avara1986

## Description

Add basic WAF telemetry metrics tests

## Check list

Your PR is not ready to be reviewed? Please save it as a draft :pray:

- [ ] Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
- [ ] CI is passing
- [ ] There is at least one approval from code owners

Yes to all? Feel free to merge it whenever you want :heart:

2023-02-03 10:29 UTC, cbeauchesne requested changes
Few step for a new scenario : 

* update your branch with the last version of main
* add your scenario in `utils/scripts/generate-github-action-file.py` (you'll find in it a scenario list
* run this script (it'll update ci.yaml)

Thanks !

2023-02-03 16:27 UTC, cbeauchesne commented
Finally, you want to keep a separated scenario? (cf discussion on slack)

2023-02-14 09:36 UTC, gnufede approved these changes

2023-02-14 10:21 UTC, cbeauchesne requested changes

2023-02-14 10:21 UTC, cbeauchesne commented on tests/appsec/waf/test_telemetry.py
> +def _validate_metrics(payload, language):
`language` is always equals to `context.library`

```suggestion
def _validate_metrics(payload):
```

2023-02-14 10:21 UTC, cbeauchesne commented on tests/appsec/waf/test_telemetry.py
> +def _validate_headers(headers, language):
`language` is always equals to `context.library`

```suggestion
def _validate_metrics(payload):
```

2023-02-14 10:21 UTC, cbeauchesne commented on tests/appsec/waf/test_telemetry.py
> +        interfaces.library.validate_telemetry(validator, success_by_default=False)
`success_by_default` default value is always `False`

```suggestion
        interfaces.library.validate_telemetry(validator)
```

2023-02-15 14:43 UTC, cbeauchesne approved these changes

2023-02-20 08:12 UTC, merged