Refactor and Fix Passing Telemetry Tests
DataDog/system-tests pull request #845
Opened 2023-02-03 18:01 UTC by mehulsonowal

## Description

When looking into the telemetry tests for Go, we noticed that the tests were passing without validating on any telemetry data. This PR changes the success_by_default flag to False so that telemetry data is required to validate telemetry tests. It also refactors the test to validate on data from `get_telemetry_data()` after the weblog app is closed.

## Check list

Your PR is not ready to be reviewed? Please save it as a draft :pray:

- [ ] Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
- [ ] CI is passing
- [ ] There is at least one approval from code owners

Yes to all? Feel free to merge it whenever you want :heart:

2023-02-09 06:57 UTC, robertomonteromiguel requested changes
It makes sense that GraalVm tests fail, since not all features are supported yet.

Could you add this to the failed tests?

```
@missing_feature(context.weblog_variant == "spring-boot-native", reason="GraalVM. Tracing support only")
@missing_feature(context.weblog_variant == "spring-boot-3-native", reason="GraalVM. Tracing support only")
```

2023-02-14 17:22 UTC, cbeauchesne requested changes

2023-02-14 17:28 UTC, mehulsonowal commented on tests/test_telemetry.py
> +from utils.interfaces._misc_validators import HeadersPresenceValidator, HeadersMatchValidator
for some reason when i used them, it would say there was no data to validate on

2023-02-15 14:45 UTC, cbeauchesne approved these changes

2023-02-15 17:52 UTC, robertomonteromiguel approved these changes

2023-02-15 18:04 UTC, merged