parametric: added parametric tests for otel api
DataDog/system-tests pull request #861
Opened 2023-02-09 14:38 UTC by lievan

## Description

Added tests for starting/ending parent and child spans, force flushing, and setting span status

## Check list

Your PR is not ready to be reviewed? Please save it as a draft :pray:

- [ ] Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
- [ ] CI is passing
- [ ] There is at least one approval from code owners

Yes to all? Feel free to merge it whenever you want :heart:

2023-02-09 15:17 UTC, dianashevchenko requested changes

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/otel_methods.go
> +	// if attrs := args.GetAttributes(); attrs != nil {
Current api allows passing in the attributes at the start, it's fin to continue with it

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/otel_methods.go
> +			span.SetAttributes(attribute.StringSlice(k, inp))
The most common scenario would be a singular bool, int, etc.
```suggestion
			inp := make([]string, n)
			for _, v := range lv.GetVal() {
				inp = append(inp, v.GetStringVal())
			}
			if len(inp) == 1{
			span.SetAttributes(attribute.String(k, inp[0]))
			}
			span.SetAttributes(attribute.StringSlice(k, inp))
```

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/otel_methods.go
> +func (s *apmClientServer) OtelSetName(ctx context.Context, args *OtelSetNameArgs) (*OtelSetNameReturn, error) {
A note to check - Otel component == ddtrcae operation name

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/otel_methods.go
> +	set_flush_success := func(ok bool) { success = ok }
if it's used once, we don't really need it

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/otel_methods.go
> +	is_recording := span.IsRecording()
Same here with one-use variable

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/otel_methods.go
> +	span_context := span.SpanContext()
Same here with one-use variable 😁

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/otel_methods.go
> +//func (s *apmClientServer) StopOtelTracer(context.Context, *StopOtelTracerArgs) (*StopOtelTracerReturn, error) {
Can probably be removed

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/tracer_methods.go
> +	if args.ParentId != nil && *args.ParentId > 0 {
```suggestion
if args.GetParentID() > 0{
```

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/apps/golang/tracer_methods.go
> +	}
```suggestion
if args.GetParentID() > 0{
```

2023-02-09 15:17 UTC, dianashevchenko commented on parametric/test_otel_tracer.py
> +# todo: add prefix_library to run otel_*
better to move constants to the spec file

2023-02-14 12:07 UTC, dianashevchenko requested changes

2023-02-14 12:08 UTC, dianashevchenko commented on parametric/test_otel_tracer.py
> +# todo: add prefix_library to run otel_*
```suggestion
```

2023-02-15 18:00 UTC, lievan commented on parametric/test_otel_tracer.py
> +    assert root_span["duration"] * (1e-9) == end_time - start_time
Created a separate file `test_otel_span_methods.py` to increase granularity!

2023-02-21 16:41 UTC, dianashevchenko commented on parametric/test_otel_span_methods.py
> +    root_span = find_span(trace, OtelSpan(name="operation"))
span = get_span(test_agent)

2023-02-21 16:42 UTC, dianashevchenko commented on parametric/test_otel_span_methods.py
> +            parent.finish(timestamp=start_time + duration_s)
is it really a parent?

2023-03-07 17:53 UTC, lievan commented
Worked moved to https://github.com/DataDog/system-tests/pull/884

2023-03-07 17:53 UTC, closed without merging