Maximo/dbm apm dotnet
DataDog/system-tests pull request #908
Opened 2023-02-24 21:34 UTC by link04

## Description

For the `dotnet` sample app I `DbmEndpoint.cs` class with a `/dbm` endpoint to test that both MySql and Postgres spans are being tagged as expected when `DD_DBM_PROPAGATION_MODE` is set to `full`.

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if needed.

Once your PR is reviewed, you can merge it ! :heart:

2023-03-03 08:56 UTC, cbeauchesne requested changes

2023-03-03 08:56 UTC, cbeauchesne commented on tests/integrations/test_dbm.py
> +        assert self.requests, "Requests were not submit for {}. Please disable this test for this library "
`assert <array>` is always true (and actually, requests in this array will always be submitted). 

I think the test above is enough.

2023-03-03 15:27 UTC, link04 commented on tests/integrations/test_dbm.py
> +        assert self.requests, "Requests were not submit for {}. Please disable this test for this library "
Thank you for the review, I removed it then ran the tested that the tests still passed:
https://github.com/DataDog/system-tests/pull/908/commits/59f875455b48a572074988cb348a63dd0da44632

2023-03-03 17:16 UTC, cbeauchesne commented
CI is failing on the modified test, right ? I set back this PR to draft, you can put it back as normal when it's fixed. If you need any help, please ping me on slack :)

2023-03-08 10:34 UTC, cbeauchesne commented
And also, I'll handle the conflict. Ping me when the PR is ready.

2023-03-10 15:04 UTC, link04 commented on tests/integrations/test_dbm.py
> +    context.library in ["python", "nodejs"] and context.weblog_variant != "flask-poc", reason="Missing on weblog",
I based this branch out of  https://github.com/DataDog/system-tests/compare/moon/extend-dbm-system-tests?expand=1 which the owner prepared so that the tests for .NET and Node can be added, right after I merge this PR the person working on the Node test will make their PR with the test which they already completed. Should I removed it and let that person change it instead?

2023-03-10 17:11 UTC, cbeauchesne commented on tests/integrations/test_dbm.py
> +    context.library in ["python", "nodejs"] and context.weblog_variant != "flask-poc", reason="Missing on weblog",
Up to you :)

2023-03-10 17:12 UTC, cbeauchesne commented on tests/integrations/test_dbm.py
> +    context.library in ["python", "nodejs"] and context.weblog_variant != "flask-poc", reason="Missing on weblog",
Actually, the CI is failing on .NET

2023-03-20 17:05 UTC, cbeauchesne commented
The CI is still failing => converting to draft. If you need any help, please ping me on slack.

2023-04-20 16:15 UTC, cbeauchesne commented
Let me handle the conflict

2023-04-20 16:17 UTC, cbeauchesne commented
conflict ok. Is this PR ready to be reviwed? if yes, please convert it it normal PR, I'll review asap.

2023-04-24 16:41 UTC, cbeauchesne commented
mysqldb takes 15s to start, it very likely the issue. Adding a commit soon to fix that

2023-04-25 13:31 UTC, merged