app product change test
DataDog/system-tests pull request #927
Opened 2023-03-02 16:17 UTC by aditim16

## Description

Assert that this event app-product-change is emitted when a product is enabled 

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if needed.

Once your PR is reviewed, you can merge it ! :heart:

2023-03-07 16:40 UTC, cbeauchesne requested changes

2023-03-07 17:20 UTC, aditim16 commented on tests/test_telemetry.py
> +            self.validate_library_telemetry_data(validator)
fixed it

2023-03-08 10:31 UTC, cbeauchesne requested changes

2023-03-08 10:31 UTC, cbeauchesne commented on tests/test_telemetry.py
> +    @bug(
When an endpoint is missing, we categorize it as missing feature.

```suggestion
    @missing_feature(context.library in ("dotnet", "nodejs", ...),   reason="weblog GET/enable_product and app-product-change event is not implemented yet.")
```

2023-03-09 14:53 UTC, cbeauchesne requested changes

2023-03-09 14:53 UTC, cbeauchesne commented on tests/test_telemetry.py
> +        context.library in ("dotnet", "nodejs", "java", "python"),
All of them, as no tracer implemented yet this feature

2023-03-09 14:53 UTC, cbeauchesne commented on tests/test_telemetry.py
> +                for prod in products > 0:
```suggestion
                for prod in products:
```

2023-03-09 14:53 UTC, cbeauchesne commented on tests/test_telemetry.py
> +                    assert appsecEnabled == True, f"Product appsec enabled flag is {appsecEnabled}"
```suggestion
                    assert appsecEnabled is True, f"Product appsec enabled flag is {appsecEnabled}"
```

2023-03-09 14:53 UTC, cbeauchesne commented on tests/test_telemetry.py
> +                    ), f"Product appsec enabled flag is {dynamicInstrumentationEnabled}"
better error message is like "dynamic_instrumentation was expected to be False, found True"

2023-03-09 14:53 UTC, cbeauchesne commented on tests/test_telemetry.py
> +    def setup_app_product_change(self):
Can you do a dedicated scenario with appsec, profiling ... set to false at startup time.

2023-03-09 14:53 UTC, cbeauchesne commented on tests/test_telemetry.py
> +            else:
Remove this part, and add another line 

```
    self.validate_library_telemetry_data(lambda data: data["request"]["content"].get("request_type") == "app-product-change")
```

2023-03-14 16:40 UTC, cbeauchesne commented
Could you resolve the conflict before I review it please ? 🙏

2023-03-14 20:47 UTC, mehulsonowal approved these changes
small nit but LGTM!

2023-03-14 20:47 UTC, mehulsonowal commented on tests/test_telemetry.py
> +                    ), f"Product dynamic_instrumentation enabled was expected to be False, found True"
```suggestion
                for product in products:
                    appsec_enabled = product["appsec"]["enabled"]
                    profiler_enabled = product["profiler"]["enabled"]
                    dynamic_instrumentation_enabled = product["dynamic_instrumentation"]["enabled"]
                    assert (
                        appsec_enabled is True
                    ), f"Product appsec Product profiler enabled was expected to be True, found False"
                    assert profiler_enabled is True, f"Product profiler enabled was expected to be True, found False"
                    assert (
                        dynamic_instrumentation_enabled is False
                    ), f"Product dynamic_instrumentation enabled was expected to be False, found True"
```

2023-03-15 10:10 UTC, cbeauchesne requested changes

2023-03-15 10:10 UTC, cbeauchesne commented on .github/workflows/ci.yml
>      - name: Run TELEMETRY_DEPENDENCY_LOADED_TEST_FOR_DEPENDENCY_COLLECTION_DISABLED scenario
`env` is missing

2023-03-16 08:55 UTC, cbeauchesne commented
Could you resolve the conflict please ? :)

2023-03-20 17:07 UTC, cbeauchesne commented
CI is failing on `spring-boot-3-native` and `spring-boot-native`, if it's expected, can add the in `missing_feature` please ?

2023-03-23 16:39 UTC, cbeauchesne commented
CI is still failing on java native 3

2023-03-24 11:02 UTC, cbeauchesne approved these changes

2023-03-24 16:37 UTC, merged