Add docs how to use a custom Java Tracer with parametric tests
DataDog/system-tests pull request #936
Opened 2023-03-03 22:49 UTC by ygree

## Description

Adds notes on how to use a custom Java Tracer with parametric tests

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if needed.

Once your PR is reviewed, you can merge it ! :heart:

2023-03-06 08:03 UTC, PerfectSlayer requested changes
Good idea. I will add more details about the client config itself later.
Just a minor change request.

2023-03-06 08:03 UTC, PerfectSlayer commented on parametric/README.md
> +./gradlew :dd-trace-api:jar
Can you add the clone command first?
```bash
git clone git@github.com:DataDog/dd-trace-java.git
cd dd-trace-java && ./gradlew :dd-trace-ot:shadowar :dd-trace-api:jar
```

2023-03-06 18:20 UTC, ygree commented on parametric/README.md
> +./gradlew :dd-trace-api:jar
Good idea!

2023-03-07 07:44 UTC, PerfectSlayer approved these changes

2023-03-07 16:42 UTC, cbeauchesne approved these changes

2023-03-20 20:15 UTC, Kyle-Verhoog approved these changes

2023-03-20 20:16 UTC, merged